### PR TITLE
Show linked prompts in the run page

### LINKED ISSUE #16361: [BUG] MLFlow not logging usage of loaded prompts
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 3.1.0
- Tracking server: 3.1.0
The tracking server is running from the docker image `ghcr.io/mlflow/mlflow:v3.1.0`.

### System information

- **OS Version**: Linux Ubuntu
- **Python version**: 3.10.12

### Describe the problem

When using `mlflow.genai.load_prompt`, there is no indication on the MLFlow web UI that the prompt was used in connection with that run. Refer to the code examples and absence of information in the screenshots from the UI.

These screenshots from the UI demonstrates *expected behavior* that was experienced earlier this month. Note that this run was performed with a 2 version of mlflow, and that we've since migrated out client and server versions to 3.1.0.

Image

Image

### Tracking information

```shell
System information: Linux Ubuntu
Python version: 3.10.12
MLflow version: 3.1.0
MLflow module location: /home/sfarnsworth/venv/lib/python3.10/site-packages/mlflow/__init__.py
Tracking URI: http://localhost:6300
Registry URI: http://localhost:6300
MLflow environment variables: 
  MLFLOW_EXPERIMENT_ID: 525197603655632536
  MLFLOW_TRACKING_URI: http://localhost:6300
MLflow dependencies: 
  Flask: 2.3.3
  aiohttp: 3.9.3
  alembic: 1.13.1
  docker: 6.1.3
  fastapi: 0.110.0
  graphene: 3.4.3
  gunicorn: 20.1.0
  kubernetes: 29.0.0
  langchain: 0.1.9
  matplotlib: 3.8.3
  mlflow-skinny: 3.1.0
  numpy: 1.26.4
  pandas: 2.2.3
  pyarrow: 11.0.0
  scikit-learn: 1.4.1.post1
  scipy: 1.12.0
  sqlalchemy: 2.0.27
  tiktoken: 0.7.0
  uvicorn: 0.27.1
  virtualenv: 20.29.1
  watchfiles: 0.21.0

```

### Code to reproduce issue

```ipython
In [1]: import mlflow
   ...: mlflow.set_tracking_uri("http://localhost:6300")
   ...: mlflow.set_experiment("steele-tests")

In [2]: with mlflow.start_run():
   ...:     prompt = mlflow.genai.load_prompt(f"prompts:/reproduce-error-prompt@production").format()
   ...:     print(prompt)
   ...: 
This is an example prompt.
🏃 View run casual-pug-161 at: http://localhost:6300/#/experiments/525197603655632536/runs/6b8e763d153a449c8f372a9319af82c0
🧪 View experiment at: http://localhost:6300/#/experiments/525197603655632536

In [3]: with mlflow.start_run():
   ...:     prompt = mlflow.genai.load_prompt(f"prompts:/reproduce-error-prompt/2").format()
   ...:     print(prompt)
   ...: 
This is a new version of the example prompt.
🏃 View run loud-croc-600 at: http://localhost:6300/#/experiments/525197603655632536/runs/8ced3ff8c7f84d44a755d30ae0d23d15
🧪 View experiment at: http://localhost:6300/#/experiments/525197603655632536
```

Image

Image

Image

Image

### Stack trace

None

### Other info / logs

None

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by TomeHirata**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/TomeHirata/mlflow/pull/16410?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/16410/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/16410/merge#subdirectory=skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/16410/merge
```

</p>
</details>

### Related Issues/PRs

Resolve #16361

### What changes are proposed in this pull request?

Since https://github.com/mlflow/mlflow/pull/16168/files, the linkage between prompt versions and runs are stored as a run tag, and the UI has been failing to display the linkage properly. This PR fixes the issue.

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

image

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/pages/prompts/utils.ts [hunk 1]
```diff
@@ -24,3 +27,25 @@ export enum PromptVersionsTableMode {
...
+
+  try {
+    const promptVersions = JSON.parse(linkedPromptsTag.value);
+    if (Array.isArray(promptVersions)) {
+      return promptVersions.filter(
+        (prompt: any) => prompt && typeof prompt.name === 'string' && typeof prompt.version === 'string',
+      );
+    }
+  } catch (error) {
+    console.warn('Failed to parse linked prompts from run tags:', error);
```
Comment (BenWilson2) [inline mlflow/server/js/src/experiment-tracking/pages/prompts/utils.ts:47]: +1

**Review by BenWilson2 — APPROVED** [review]
Looks solid!
