### PR TITLE
[Issue #3170] PDF viewer doesn't render PDFs in MLflow 1.10

### LINKED ISSUE #3170: [BUG] PDF worker file can't be found when running MLflow UI server
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No, use the diabetes example.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Catalina
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.10
- **Python version**: 3.6
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.

An error claiming that the PDF is unable to be loaded occurs when running in the mlflow binary. I was able to reproduce this with the latest version of MLflow, but the PDF loads correctly when running MLflow from source. It appears that the server is not serving the files correctly when running from the binary. 

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Change the diabetes example to save figure as a PDF and log the artifact as a PDF. View the UI and notice how it doesn't work.

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations

### PR DESCRIPTION
**Pull request by ankit-db**
Signed-off-by: Ankit Mathur <ankit.mathur@databricks.com>

In the built version of MLflow, we serve static files from `static-files/`, and so, for those OSS users who use the pip package (basically all of them), viewing PDFs won't work, since the request is sent to: `localhost:5000/pdf.worker.js`, which works when running MLflow from source.

This PR changes this to use the public URL which is used in [other parts of the code](https://github.com/mlflow/mlflow/blob/HEAD/mlflow/server/js/public/index.html#L6).

## How is this patch tested?

Manual with both bdist and dev setup

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by ankitmathur-db** [comment]
Thanks @harupy for suggesting a more comprehensive fix!

**Comment by harupy** [comment]
I have confirmed the proposed fix works for both dev and dist environments by:

1. Running `npm start` (dev env)
2. Installing `mlflow` using a wheel file built by `python setup.py bdist_wheel`, and running `mlflow ui` (dist env)

**Comment by ankitmathur-db** [comment]
Yeah verified the same as @harupy as well

**Review by harupy — APPROVED** [review]
LGTM

File: mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.js [hunk 1]
```diff
@@ -2,11 +2,13 @@ import React, { Component } from 'react';
 import PropTypes from 'prop-types';
 import './ShowArtifactImageView.css';
 import { getSrc } from './ShowArtifactPage';
-import { Document, Page } from 'react-pdf';
+import { Document, Page, pdfjs } from 'react-pdf';
 import { Pagination, Spin } from 'antd';
 import { getArtifactBytesContent } from './ShowArtifactUtils';
 import './ShowArtifactPdfView.css';
 
+pdfjs.GlobalWorkerOptions.workerSrc = `${process.env.PUBLIC_URL}/pdf.worker.js`;
```
Comment (Zangr) [inline mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.js:10]: Can we provide some comments with a link to the documentation of how `workerSrc` should be used?

Comment (ankitmathur-db) [reply mlflow/server/js/src/experiment-tracking/components/artifact-view-components/ShowArtifactPdfView.js:12]: Done!

**Review by Zangr — APPROVED** [review]
LGTM
