### PR TITLE
Show images in the metric tab

### LINKED ISSUE #15013: [BUG] Images are not displayed in Experiment model metric tab
### MLflow version

2.21.1.dev0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Python version**: 3.9
- **yarn version, if running the dev UI**: 1.22

### Describe the problem

Image

Images are not displayed in Experiment model metric tab

### Steps to reproduce the bug

- create an `a.png` in the directory
- Run the following code locally

```python
from PIL import Image, ImageFilter

import mlflow
mlflow.set_experiment("MLflow Quickstart")

image = Image.open("./a.png")

# Start an MLflow run
with mlflow.start_run():
    mlflow.log_image(image, key="dogs", step=3)

```

- Go to experiment model metric tab
- The image is not displayed

### Code to generate data required to reproduce the bug

_No response_

### Is the console panel in DevTools showing errors relevant to the bug?

_No response_

### Does the network panel in DevTools contain failed requests relevant to the bug?

_No response_

### PR DESCRIPTION
**Pull request by TomeHirata**
### Related Issues/PRs

Resolve #15013

### What changes are proposed in this pull request?

There is an issue that images are not displayed correctly on the run metrics tab. This is caused by incorrectly decoding the file name that uses "%" as the separator. The full resolution needs replacing the separator, but this PR fixes the immediate issue.

image

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

image

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Show images in the run metrics tab.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/reducers/ImageReducer.ts [hunk 1]
```diff
@@ -30,8 +30,10 @@ const parseImageFile = (filename: string) => {
   if (delimiter === undefined) {
     throw new ImagePathParseError('Logged image path parse: incorrect filename format for image file', filename);
   }
-  const [serializedImageKey, stepLabel, stepString, timestampLabel, timestampString, _, compressed] =
-    fileKey.split(delimiter);
+  // The variables retrieved here are not reliable on OSS due to the usage of "%" as the separator.
+  // Need to switch to a different separator on the backend to fully resolve the issue.
+  const [serializedImageKey, stepLabel, stepString, timestampLabel, timestampString, ..._] = fileKey.split(delimiter);
+  const isCompressed = fileKey.includes('compressed');
```
Comment (B-Step62) [inline mlflow/server/js/src/experiment-tracking/reducers/ImageReducer.ts:36]: Is there any additional rule to limit the false positive here? E.g. what if the original users' image name is `pic_compressed.png`. Maybe we can limit the match target here to the `..._` part not the entire `fileKey`?

Comment (TomeHirata) [reply mlflow/server/js/src/experiment-tracking/reducers/ImageReducer.ts]: Images logged through `log_image(artifact_path="...")` is not relevant to this change as this logic is for images with key and step. To handle the case where "key" includes "compressed" keyword, I changed "includes" to "endWith"

**Review by B-Step62 — APPROVED** [review]
LGTM!
