### PR TITLE
Fix UI crashes / inconsistencies related to path normalization

### LINKED ISSUE #3919: [BUG] UI crashes as soon as the model is registered via API
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NAME="Amazon Linux" VERSION="2" ID_LIKE="centos rhel fedora"
- **MLflow installed from (source or binary)**:
- **MLflow version (run ``mlflow --version``)**: mlflow, version 1.13
- **Python version**: Python 3.7.9
- **npm version, if running the dev UI**: N/A
- **Exact command to reproduce**:

### Describe the problem
UI crashes as soon as the model is registered via API.  UI works fine when the model is registered via UI.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
from mlflow.tracking.client import MlflowClient
client = MlflowClient()
client.create_registered_model("HPP")
result = client.create_model_version(name="HPP",
source="s3://sagemaker-us-east-1-830861431234/mlruns/6dcb10fbc2b24f46bb4b29ed0ed54268/artifacts/model/",
run_id="6dcb10fbc2b24f46bb4b29ed0ed54268")

```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Screen Shot 2020-12-28 at 4 40 56 PM

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by dbczumar**
## What changes are proposed in this pull request?

As outlined in #3919, the MLflow UI's experiment runs compact view table contains brittle artifact path comparison logic that does not handle the case where two artifact paths are semantically equivalent but syntactically different, which can happen if one artifact path contains duplicate forward slashes or trailing slashes.

Similar brittle comparison logic exists in MLflow's artifact viewer. If a model version exists with source `/tmp/foo///bar/` and a run artifact with path `/tmp/foo/bar` is examined in the MLflow Artifact Viewer, this run artifact won't be associated with the model version in the UI (instead of seeing version info, users see the blue "Register Model" button, as if no existing versions are associated with it).

This PR fixes #3919 and addresses the artifact viewer issue.

## How is this patch tested?

Unit tests pending

## Release Notes

Fix experiment UI crash and artifact viewer inconsistency when model versions sources and run artifact paths differ by trailing or duplicate slashes.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [X] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [X] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [X] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ import { RunInfo } from '../sdk/MlflowMessages';
 import { Link } from 'react-router-dom';
 import Routes from '../routes';
 import Utils from '../../common/utils/Utils';
+import { normalize } from '../../common/utils/FileUtils';
```
Comment (dbczumar) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:10]: Will remove this - migrated `normalize` from `FileUtils` to `Utils`.

File: mlflow/server/js/src/common/utils/Utils.js [hunk 2]
```diff
@@ -156,6 +156,18 @@ class Utils {
...
   }
 
+  /**
+   * Normalizes a URI, removing redundant slashes and trailing slashes
+   * For example, normalize("foo://bar///baz/") === "foo://bar/baz"
+   */
+  static normalize = (uri) => {
+    // Remove redundant slashes while ensuring that double slashes immediately following
+    // the scheme component are preserved
+    const without_redundant_slashes = uri.replace(/([^:]\/)\/+/g, '$1');
```
Comment (xanderwebs) [inline mlflow/server/js/src/common/utils/Utils.js:166]: I think we tend to use camelCase over snake_case in terms of variable naming.

File: mlflow/server/js/src/common/utils/Utils.js [hunk 3]
```diff
@@ -156,6 +156,18 @@ class Utils {
     return path.replace(/(.*[^/])\.[^/.]+$/, '$1');
   }
 
+  /**
+   * Normalizes a URI, removing redundant slashes and trailing slashes
+   * For example, normalize("foo://bar///baz/") === "foo://bar/baz"
+   */
+  static normalize = (uri) => {
```
Comment (xanderwebs) [inline mlflow/server/js/src/common/utils/Utils.js:163]: nit: this doesn't seem to need to be bound to this particular class. can you just do

```js
static normalize(url) {
   ...
}```

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js [hunk 4]
```diff
@@ -591,28 +592,34 @@ export function ModelsCellRenderer(props) {
...
+        (model) => Utils.normalize(model['artifact_path']) === normalizedSourceArtifactPath,
       );
+      if (matchingModels.length > 0) {
+        [loggedModel] = matchingModels;
+        registeredModelDiv = (
+          <>
+            {' - '}
+            <img
+              data-test-id='registered-model-icon'
+              alt=''
```
Comment (xanderwebs) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:607]: nit: I know you didn't technically add this, but can you add some alt-text here?  It's typically bad practice to leave alt text blank

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js [hunk 5]
```diff
@@ -591,28 +592,34 @@ export function ModelsCellRenderer(props) {
...
-            {`/${version}`}
-          </a>
-        </>
+
+      const normalizedSourceArtifactPath = Utils.normalize(registeredModelSource).split(`${runId}/artifacts/`)[1];
+      const matchingModels = loggedModels.filter(
+        (model) => Utils.normalize(model['artifact_path']) === normalizedSourceArtifactPath,
       );
+      if (matchingModels.length > 0) {
+        [loggedModel] = matchingModels;
```
Comment (xanderwebs) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:601]: could you add a `let` in front of this line?

**Review by xanderwebs — COMMENTED** [review]
Left some minor comments -- you might need to run prettier to fix some coding style issues.

**Review by dbczumar — COMMENTED** [review]
@xanderwebs Thanks for the review! Addressed your comments!

**Review by xanderwebs — APPROVED** [review]
LGTM!
