### PR TITLE
Fix issue with aliases not appearing in table of model versions within registered model detail page

### LINKED ISSUE #10961: [BUG] Alias for model version doesn't show up in the table
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.9.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 10 (buster)
- **Python version**: 3.9.18

### Describe the problem

Inside the Models section when a certain model is selected there is a pivot table with model versions, their tags and aliases. After assigning an alias via button "Add" from UI or from code using client.set_registered_model_alias method, the alias doesn't show up in the pivot table. 

When I click the button "Add" for the model version I've just assigned the alias, the alias becomes visible in search panel as if it was actually assigned. The method client.get_model_version_by_alias also return the correct alias.

So, the problem is that column "Aliases" won't display any aliases even if they are set.

The expected behavior is the following: after setting an alias it should be displayed in the pivot table similarly to the "Tags" column.

### Steps to reproduce the bug

https://github.com/mlflow/mlflow/assets/147606144/c48be945-1dd3-4dd7-b046-99e0211d431a

### Code to generate data required to reproduce the bug

_No response_

### Is the console panel in DevTools showing errors relevant to the bug?

_No response_

### Does the network panel in DevTools contain failed requests relevant to the bug?

_No response_

### PR DESCRIPTION
**Pull request by smurching**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/smurching/mlflow/pull/11223?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/11223/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 11223
```

</p>
</details>

### Related Issues/PRs

See title; fixes https://github.com/mlflow/mlflow/issues/10961

With the fix, I'm able to set/delete aliases in the UI after:
* Running the MLflow server against a SQL backend via `mlflow server --backend-store-uri sqlite:////tmp/mlflow.sqlite`
* Running the local development UI via `cd mlflow/server/js && yarn start`

image

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

### Does this PR require documentation update?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/model-registry/components/ModelVersionTable.tsx [hunk 1]
```diff
@@ -226,11 +238,12 @@ export const ModelVersionTable = ({
           }),
           meta: { styles: { flex: 2 }, multiline: true },
           cell: ({ getValue, row: { original } }) => {
+            const mvAliases = aliasesByVersion[original.version] || [];
             return (
               <ModelVersionTableAliasesCell
                 modelName={modelName}
                 version={original.version}
-                aliases={getValue() as string[]}
```
Comment (smurching) [inline mlflow/server/js/src/model-registry/components/ModelVersionTable.tsx:233]: The existing logic assumes `SearchModelVersions` will return a list of aliases per model version, which is not guaranteed/unfortunately inconsistent between MLflow backend implementations. In particular, we don't return aliases attached to each model version in `SearchModelVersions` in SQL-based backend stores for performance reasons. It seems we ignore such implications and return them in the FileStore, leading to inconsistency. The fix here is to just rely on the overall list of aliases attached to the parent registered model & reference those here

**Comment by smurching** [comment]
@hubertzub-db FYI turned out the fix for this issue was in the UI after all - I got started on a fix PR ^here, just haven't gotten to write tests etc yet

**Review by hubertzub-db — APPROVED** [review]
Looks good, thanks for the fix 🚀! One ask: it'd be good to update the `useMemo` for `tableColumns` dependency list with new `aliasesByVersion` variable (I believe eslint should complain there)
