### PR TITLE
Fix experiment list pagination reset when search/filter criteria changes

### LINKED ISSUE #18514: [BUG] Experiment listing page pagination broken after updating search criteria
### MLflow version

3.5.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian Trixie
- **Python version**: 3.19.9
- **yarn version, if running the dev UI**:

### Describe the problem

Hello mlflow devs, I'm reporting a UI bug that I found in the new post-3.2.0 experiments listing page. The new UI is much improved and much appreciated, but I did notice that sometimes I'm failing to find an experiment that I *know* is there (i.e., I can get there by adding the experiment number to the URL) via an exact name.

After some fiddling with browser dev tools, I think I realized the problem:

When I add or update a search name filter in the UI text box, the UI will add this additional filter criteria to the search query. **However, it will not reset the pagination token.** This is problematic because if the thing you're looking for only exists **before** the current pagination token, you'll get a "No results found" screen with no recourse to to back to the first page (the pagination UI will be hidden in this case). Only with a browser page refresh can you get rid of your current pagination token and start over.

_How this presented to me initially is that:_ when you have a ton of experiments, and you're paging through them, updating search criteria as you go, sometimes (seemingly random) you'll just get the "No results found" screen even though you know for sure it should exist. Tweaking the search string will do often do nothing. But once you refresh the page, mysteriously you'll be able to find that experiment again.

### Steps to reproduce the bug

1. Make sure you have plenty of experiments to paginate over. Go to the experiments overview listing page
2. Pick an experiment on the first page and copy its exact name
3. Click "next page" several times to navigate forward
4. Now paste in the experiment name you picked in (2) into the search box. It should fail to find the experiment and you'll see the "No results found" screen, with no way to navigate back to the first page
5. Refresh the browser page, and type in the search criteria again. You should now be able to find the experiment.

### Code to generate data required to reproduce the bug

_No response_

### Is the console panel in DevTools showing errors relevant to the bug?

_No response_

### Does the network panel in DevTools contain failed requests relevant to the bug?

Query request for experiment listing after paginating for a bit:

Image

Now type in a search keyword, and press enter. The new query request retains the old pagination token

Image

### PR DESCRIPTION
**Pull request by serena-ruan**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/serena-ruan/mlflow/pull/18526?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/18526/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/18526/merge#subdirectory=libs/skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/18526/merge
```

</p>
</details>

### Related Issues/PRs

Resolve #18514

### What changes are proposed in this pull request?

Reset pagination to page 1 when users update search filters, tag filters, or sorting on the experiments listing page. Previously, changing filters retained the pagination token, causing "No results found" if matching experiments were on earlier pages.

Before:
image

After:
image

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [ ] Manual tests

Added comprehensive test suite in `useExperimentListQuery.test.tsx` covering:
- Pagination reset on search filter change
- Pagination reset on tag filter change
- Pagination reset on sorting change
- Forward/backward pagination controls
- API query construction

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Fixed pagination bug in experiments listing page where search/filter changes did not reset to page 1, causing "No results found" errors.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] \`area/tracking\`: Tracking Service, tracking client APIs, autologging
- [ ] \`area/models\`: MLmodel format, model serialization/deserialization, flavors
- [ ] \`area/model-registry\`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] \`area/scoring\`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] \`area/evaluation\`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] \`area/gateway\`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] \`area/prompts\`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] \`area/tracing\`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] \`area/projects\`: MLproject format, project running backends
- [x] \`area/uiux\`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] \`area/build\`: Build and test infrastructure for MLflow
- [ ] \`area/docs\`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] \`rn/none\` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] \`rn/breaking-change\` - The PR will be mentioned in the "Breaking Changes" section
- [ ] \`rn/feature\` - A new user-facing feature worth mentioning in the release notes
- [x] \`rn/bug-fix\` - A user-facing bug fix worth mentioning in the release notes
- [ ] \`rn/documentation\` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useExperimentListQuery.ts [hunk 1]
```diff
@@ -95,6 +95,40 @@ export const useExperimentListQuery = ({
...
+      previousPageTokens.current = [];
+
+      // Update ref with current values
+      prevFiltersRef.current = {
+        searchFilter,
+        tagsFilter,
+        sorting: currentSortingSerialized,
+      };
+    }
+  }, [searchFilter, tagsFilter, sorting]);
```
Comment (daniellok-db) [inline mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useExperimentListQuery.ts]: hmm i wonder if needs to be this complex. rather than doing custom comparison with a ref, can we try just using a normal `useEffect` depending on `[searchFilter, tagsFilter, sorting]`? i took a quick look and i don't think `tagsFilter` nor `sorting` should change references unnecessarily. can we try with the following code and see if it behaves properly (e.g. it doesn't reset when it's not supposed to)?

```suggestion
  // Reset pagination when filters or sorting changes
  useEffect(() => {
      setCurrentPageToken(undefined);
      previousPageTokens.current = [];
  }, [searchFilter, tagsFilter, sorting]);
```

Comment (daniellok-db) [reply mlflow/server/js/src/experiment-tracking/components/experiment-page/hooks/useExperimentListQuery.ts]: discussed offline, claude already tried this. i would suggest to find out which param (`tagsFilter` or `sorting`) causes the change and make sure that's properly memoized rather than doing custom comparison

**Review by daniellok-db — APPROVED** [review]
lgtm!
