### PR TITLE
display artifact previews even if extension is upper case

### LINKED ISSUE #1618: Artifact preview not working for uppercase extentions
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS

- **MLflow installed from (source or binary)**: binary (pypi)
- **MLflow version (run ``mlflow --version``)**: 1.0.0
- **Python version**: Python 3.6.8

### Describe the problem
Take an image file, e.g. `image.jpg` and copy it to the artifacts folder of one of the runs. Run `mlflow ui` and verify that the image is rendered in the artifacts view.

Change the extension of the image file to upper case, e.g. change `image.jpg` to `image.JPG` and refresh the artifacts view in the mlflow UI. The image is not rendered any more.

### PR DESCRIPTION
**Pull request by ankit-db**
## What changes are proposed in this pull request?
 
Resolve #1618
 
## How is this patch tested?
 
Manually:
Screen Shot 2019-07-30 at 3 12 57 PM

 
### Is this a user-facing change? 

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)
 
### What component(s) does this PR affect?
 
- [x] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactPage.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ class ShowArtifactPage extends Component {
 
   render() {
     if (this.props.path) {
-      if (IMAGE_EXTENSIONS.has(getExtension(this.props.path))) {
+      if (IMAGE_EXTENSIONS.has(getExtension(this.props.path).toLowerCase())) {
```
Comment (Zangr) [inline mlflow/server/js/src/components/artifact-view-components/ShowArtifactPage.js]: Is `getExtension(this.props.path)` guarantteed to be non-Null?

Comment (ankitmathur-db) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactPage.js]: Addressed!

**Review by Zangr — APPROVED** [review]
LGTM
