### PR TITLE
fix for missing run name in csv export

### LINKED ISSUE #813: When donwloading CSV from mlflow tracking, "Name" columns is always NULL
Working on Windows, MLFlow version 0.8.1, python 3.6.7

As described in the title, "Name" field (of a single run) is not downloaded as other run parameters/metrics are.

Thanks

### LINKED ISSUE #856: CSV export of experiment data missing `Run Name` data
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.2
- **MLflow installed from (source or binary)**: Docker Container built from mlflow Dockerfile
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2.dev0
- **Python version**: Python 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:
Extract files from [this file](https://drive.google.com/open?id=19UzTVVfPf2PMxPTJmcT7SKA-bMcMz6lC) into a directory.  Execute `mlflow run .`

### Describe the problem
`mlflow ui` display contains `Run Name` value
screen shot 2019-01-29 at 22 50 21

CSV export of the data, `Run Name` column is blank
screen shot 2019-01-29 at 22 50 36

### Source code / logs
```
(base) root@730111e49090:/opt/project/mwe_first_run_name_error# mlflow run .
2019/01/30 03:28:50 INFO mlflow.projects: === Creating conda environment mlflow-baa16dc82d9caecd97bab4d7e2e3fa6b646179c2 ===
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.1

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
certifi-2018.11.29   | 146 KB    | ##################################################################################################### | 100%
ca-certificates-2018 | 123 KB    | ##################################################################################################### | 100%
python-3.6.8         | 34.4 MB   | ##################################################################################################### | 100%
wheel-0.32.3         | 35 KB     | ##################################################################################################### | 100%
libedit-3.1.20181209 | 188 KB    | ##################################################################################################### | 100%
setuptools-40.6.3    | 625 KB    | ##################################################################################################### | 100%
xz-5.2.4             | 366 KB    | ##################################################################################################### | 100%
pip-18.1             | 1.8 MB    | ##################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting mlflow (from -r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/dd/a8/1cb5f997023c6d6c99eb49635bb5aac093efc7a7d94e1a9b9d3aaaedfd94/mlflow-0.8.1.tar.gz (11.6MB)
    100% |████████████████████████████████| 11.6MB 3.3MB/s
Collecting click>=6.7 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting databricks-cli>=0.8.0 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5f/14/7cc3d43a60156ce23b76f613fbc37ed007e298a7a51ea04a1a5bb9d0a485/databricks-cli-0.8.3.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 18.2MB/s
Collecting requests>=2.17.3 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 17.9MB/s
Collecting six>=1.10.0 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting gunicorn (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl
Collecting Flask (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting numpy (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7b/74/54c5f9bb9bd4dae27a61ec1b39076a39d359b3fb7ba15da79ef23858a9d8/numpy-1.16.0-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 2.5MB/s
Collecting pandas (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f9/e1/4a63ed31e1b1362d40ce845a5735c717a959bda992669468dae3420af2cd/pandas-0.24.0-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 5.9MB/s
Collecting scipy (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/67/e6/6d4edaceee6a110ecf6f318482f5229792f143e468b34a631f5a0899f56d/scipy-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (26.6MB)
    100% |████████████████████████████████| 26.6MB 2.2MB/s
Collecting scikit-learn (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0d/3a/b92670f5c368c20329ecc4c255993fae7934564d485c3ed7ea7b8da7f741/scikit_learn-0.20.2-cp36-cp36m-manylinux1_x86_64.whl (5.4MB)
    100% |████████████████████████████████| 5.4MB 7.1MB/s
Collecting python-dateutil (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Collecting protobuf>=3.6.0 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c2/f9/28787754923612ca9bfdffc588daa05580ed70698add063a5629d1a4209d/protobuf-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 6.0MB/s
Collecting gitpython>=2.1.0 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl
Collecting pyyaml (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Collecting boto3>=1.7.12 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a8/8a/730acf258088f2b0615e1bf6acaa63e336a97b6eeb41ce4c5b7e8b636476/boto3-1.9.86-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 8.5MB/s
Collecting querystring_parser (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/57/64/3086a9a991ff3aca7b769f5b0b51ff8445a06337ae2c58f215bcee48f527/querystring_parser-1.2.3.tar.gz
Collecting simplejson (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz
Collecting mleap>=0.8.1 (from mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/3b/17/486a3cf30695581f029ba618ee878252a9e9f859c48913e30a07d13c8a21/mleap-0.8.1.tar.gz
Collecting tabulate>=0.7.7 (from databricks-cli>=0.8.0->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c2/fd/202954b3f0eb896c53b7b6f07390851b1fd2ca84aa95880d7ae4f434c4ac/tabulate-0.8.3.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 7.1MB/s
Collecting configparser>=0.3.5 (from databricks-cli>=0.8.0->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/43/63/220afe02a0d302c2244309b1dce3d884a865be65c7d8148ededfc0c29c31/configparser-3.7.1-py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.17.3->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 15.4MB/s
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.17.3->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 10.6MB/s
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/mlflow-baa16dc82d9caecd97bab4d7e2e3fa6b646179c2/lib/python3.6/site-packages (from requests>=2.17.3->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1)) (2018.11.29)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.17.3->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 9.9MB/s
Collecting Werkzeug>=0.14 (from Flask->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from Flask->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /opt/conda/envs/mlflow-baa16dc82d9caecd97bab4d7e2e3fa6b646179c2/lib/python3.6/site-packages (from protobuf>=3.6.0->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1)) (40.6.3)
Collecting gitdb2>=2.0.0 (from gitpython>=2.1.0->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/da/30/a407568aa8d8f25db817cf50121a958722f3fc5f87e3a6fba1f40c0633e3/gitdb2-2.0.5-py2.py3-none-any.whl
Collecting botocore<1.13.0,>=1.12.86 (from boto3>=1.7.12->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d7/af/fd9c0f1f0fdc03d3367a56f35093f8b1020ba1a97ead9fa580156895944b/botocore-1.12.86-py2.py3-none-any.whl (5.2MB)
    100% |████████████████████████████████| 5.3MB 9.2MB/s
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.7.12->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3>=1.7.12->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting argparse>=1.1 (from mleap>=0.8.1->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting nose-exclude>=0.5.0 (from mleap>=0.8.1->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/63/cf/90c4be56bf11b7bc8801086d9445baf731aa36b8e8fc5791731e8e604dcd/nose-exclude-0.5.0.tar.gz
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/08/04/f2191b50fb7f0712f03f064b71d8b4605190f2178ba02e975a87f7b89a0d/MarkupSafe-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython>=2.1.0->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.86->boto3>=1.7.12->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 6.7MB/s
Collecting nose (from nose-exclude>=0.5.0->mleap>=0.8.1->mlflow->-r /opt/project/mwe_first_run_name_error/condaenv.GMr3zJ.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 8.7MB/s
Building wheels for collected packages: mlflow, databricks-cli, pyyaml, querystring-parser, simplejson, mleap, tabulate, nose-exclude
  Running setup.py bdist_wheel for mlflow ... done
  Stored in directory: /root/.cache/pip/wheels/02/be/3e/228cb7839981e16b038f5d9601cc703529f5f181f3e37a054a
  Running setup.py bdist_wheel for databricks-cli ... done
  Stored in directory: /root/.cache/pip/wheels/08/ed/d4/bcc912de9f513275d166f186d4e6c62d8a49beee6ebdacee0f
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /root/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Running setup.py bdist_wheel for querystring-parser ... done
  Stored in directory: /root/.cache/pip/wheels/ee/09/99/bf937e4f02788fa8b33dc5240842ba3977ba5c3c4ad4a115d7
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/5d/1a/1e/0350bb3df3e74215cd91325344cc86c2c691f5306eb4d22c77
  Running setup.py bdist_wheel for mleap ... done
  Stored in directory: /root/.cache/pip/wheels/bc/a5/8d/7d021f2741ed8a7354e4fe19c1890e71ed719d681cd16cf292
  Running setup.py bdist_wheel for tabulate ... done
  Stored in directory: /root/.cache/pip/wheels/2b/67/89/414471314a2d15de625d184d8be6d38a03ae1e983dbda91e84
  Running setup.py bdist_wheel for nose-exclude ... done
  Stored in directory: /root/.cache/pip/wheels/fe/b9/8f/764ed47b11e2e062ae8fe5f09d1c801a600292fdd9ba3477bb
Successfully built mlflow databricks-cli pyyaml querystring-parser simplejson mleap tabulate nose-exclude
Installing collected packages: click, idna, urllib3, chardet, requests, tabulate, six, configparser, databricks-cli, gunicorn, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, numpy, pytz, python-dateutil, pandas, scipy, scikit-learn, protobuf, smmap2, gitdb2, gitpython, pyyaml, docutils, jmespath, botocore, s3transfer, boto3, querystring-parser, simplejson, argparse, nose, nose-exclude, mleap, mlflow
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.1.0 Werkzeug-0.14.1 argparse-1.4.0 boto3-1.9.86 botocore-1.12.86 chardet-3.0.4 click-7.0 configparser-3.7.1 databricks-cli-0.8.3 docutils-0.14 gitdb2-2.0.5 gitpython-2.1.11 gunicorn-19.9.0 idna-2.8 itsdangerous-1.1.0 jmespath-0.9.3 mleap-0.8.1 mlflow-0.8.1 nose-1.3.7 nose-exclude-0.5.0 numpy-1.16.0 pandas-0.24.0 protobuf-3.6.1 python-dateutil-2.7.5 pytz-2018.9 pyyaml-3.13 querystring-parser-1.2.3 requests-2.21.0 s3transfer-0.1.13 scikit-learn-0.20.2 scipy-1.2.0 simplejson-3.16.0 six-1.12.0 smmap2-2.0.5 tabulate-0.8.3 urllib3-1.24.1
#
# To activate this environment, use
#
#     $ conda activate mlflow-baa16dc82d9caecd97bab4d7e2e3fa6b646179c2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

2019/01/30 03:29:56 INFO mlflow.projects: === Created directory /tmp/tmpEM2LCX for downloading remote URIs passed to arguments of type 'path' ===
2019/01/30 03:29:56 INFO mlflow.projects: === Running command 'source activate mlflow-baa16dc82d9caecd97bab4d7e2e3fa6b646179c2 && python mwe_first_run_name_not_recorded.py
' in run with ID '2d4c8bbccc0d4368b2734680c9dc6888' ===
run 0
run 1
run 2
run 3
2019/01/30 03:30:00 INFO mlflow.projects: === Run (ID '2d4c8bbccc0d4368b2734680c9dc6888') succeeded ===
```

### PR DESCRIPTION
**Pull request by jimthompson5802**
Fix #856, Fix #813 

@smurching Here is the proposed fix.  This is the first time I'm working in JS, not sure if I used the correct coding constructs.  

Is the following a reasonable code fragment to populate the csv export (see screenshots) with the `Run Name`?  The thing I'm uncomfortable is the use of the `row[1]` array reference.  If a future enhancement changes the order of the attributes on a row, then this code will probably break.
```
      /* add run name to export row */
      row[1] = Utils.getRunName(tagsList[index]);
```

Here here is screen shot of mlflow ui:
screen shot 2019-02-03 at 11 29 28

Here is screen shot of exported csv data
screen shot 2019-02-03 at 11 29 47

I've only tested this using the Javascript Dev Server.  I have not tried building a distributable artifact.  Do I need to build a distributable artifact to complete the PR?

### CODE REVIEW

File: mlflow/server/js/src/components/ExperimentView.js [hunk 1]
```diff
@@ -679,6 +683,10 @@ class ExperimentView extends Component {
       ];
       const paramsMap = ExperimentViewUtil.toParamsMap(paramsList[index]);
       const metricsMap = ExperimentViewUtil.toMetricsMap(metricsList[index]);
+
+      /* add run name to export row */
+      row[1] = Utils.getRunName(tagsList[index]);
```
Comment (smurching) [inline mlflow/server/js/src/components/ExperimentView.js]: Nice, this works but maybe we can just replace `runInfo.name` [here](https://github.com/mlflow/mlflow/pull/864/files#diff-fa151380130110b5b1f7ba277afb356aR678) with `Utils.getRunName(tagsList[index])`, rather than set the value and then overwrite it here

**Review by smurching — COMMENTED** [review]
@jimthompson5802 thanks for the PR & good questions! Just had one suggestion about avoiding setting & then overwriting an array element (which can be brittle as you mentioned in the PR description). Otherwise the code LGTM, and thanks for doing the manual QA - testing the dev UI should be sufficient

**Comment by jimthompson5802** [comment]
@smurching Initially I tried `Utils.getRunName(tagsList[index])` by itself.  However, that did not work.  That is why I ended with the array reference in my initial commit.

I've made the suggested change and pushed a new commit so you can see how I incorporated the change.  Below is the screen shot of the csv export with the requested change.  
screen shot 2019-02-04 at 07 19 21

**Comment by jimthompson5802** [comment]
@smurching  Looking at the code more closely, there may be an alternative way of using `Utils.getRunName(tagsList[index])`.   Right now the csv export `row` is constructed as follows (lines 676-683):
```
   const row = [
        runInfo.run_uuid,
        runInfo.name,
        runInfo.source_type,
        runInfo.source_name,
        runInfo.user_id,
        runInfo.status,
      ];
```

I can place the `getRunName` call directly in the row construction as follows:
```
    const row = [
        runInfo.run_uuid,
        Utils.getRunName(tagsList[index]), //add run name to export row
        runInfo.source_type,
        runInfo.source_name,
        runInfo.user_id,
        runInfo.status,
      ];
```

When I make this replacement, the `Run Name` shows up in the csv export.

The ideal situation would be filling the `Run Name` when the `runinfo` object is created, so that `runinfo.name` has the correct value.  Thus far, I've not been successful finding where this occurs.  I think this may occur in one of the method in `mlflow/server/js/src/reducers/Reducers.js`.

File: mlflow/server/js/src/components/ExperimentView.js [hunk 2]
```diff
@@ -679,6 +683,10 @@ class ExperimentView extends Component {
       ];
       const paramsMap = ExperimentViewUtil.toParamsMap(paramsList[index]);
       const metricsMap = ExperimentViewUtil.toMetricsMap(metricsList[index]);
+
+      //add run name to export row
+      Utils.getRunName(tagsList[index]);
```
Comment (smurching) [inline mlflow/server/js/src/components/ExperimentView.js]: Oops, sorry my last comment was unclear - I think using the logic from your last comment makes sense, i.e. we should replace `runInfo.name` on line 678 with `Utils.getRunName(...)`:

```
    const row = [
        runInfo.run_uuid,
        Utils.getRunName(tagsList[index]), // add run name to export row
        runInfo.source_type,
        runInfo.source_name,
        runInfo.user_id,
        runInfo.status,
      ];
```

It's a great point that `runInfo.name` should correctly be set to the value from the tag - to fix this we should actually modify the backend storage implementations (`mlflow/store/file_store.py` and `mlflow/store/sqlalchemy_store.py`) to read the run name from tags. Currently the REST API actually reads run name from the wrong location, hence why `runInfo.name` is set incorrectly. IMO that's actually a separate issue that's definitely worth fixing - in the short term I think the `Utils.getRunName(tagsList[index])` fix should address the CSV downloading bug

Comment (jimthompson5802) [reply mlflow/server/js/src/components/ExperimentView.js]: @smurching replaced `runInfo.name` with the call to `Utils.getRunName(tagsList[index])`

Screenshot of csv export after the change:
screen shot 2019-02-04 at 19 09 14

**Review by smurching — APPROVED** [review]
LGTM merging thanks @jimthompson5802!
