### PR TITLE
Fix runs table to resize with browser resize

### LINKED ISSUE #2405: [BUG] Runs table does not resize with browser resize
ezgif com-video-to-gif

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.5
- **MLflow installed from (source or binary)**: Source
- **MLflow version (run ``mlflow --version``)**:  1.6.1.dev0
- **Python version**: 2.7
- **npm version, if running the dev UI**: 6.9.0
- **Exact command to reproduce**: mlflow ui and npm start

### Describe the problem
The home page runs table doesn't scale with a changing browser window size. 

### Code to reproduce issue
Launch the UI in a smaller window, and then resize the window.

cc @Zangr is there a quick fix for this?

### PR DESCRIPTION
**Pull request by harupy**
Signed-off-by: harupy <17039389+harupy@users.noreply.github.com>

## What changes are proposed in this pull request?

Fixes #2405 

autofit2

## How is this patch tested?

I got [this error](https://stackoverflow.com/questions/58665089/ag-grid-jest-testing-this-btfirst-insertadjacentelement-is-not-a-function) when I tried to run the following unit test:

```
test('should call sizeColumnsToFit on window resize', () => {
    wrapper = mount(<ExperimentRunsTableMultiColumnView2 {...minimalProps} />);
    instance = wrapper.instance();
    instance.columnApi = {
      getColumnGroupState: jest.fn(() => [{ open: true }]),
    };
    instance.gridApi = {
      sizeColumnsToFit: jest.fn(),
    };
    window.dispatchEvent(new Event('resize'));
    expect(instance.gridApi.sizeColumnsToFit).toBeCalled();
  });
```

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for
Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js [hunk 1]
```diff
@@ -335,6 +335,10 @@ export class ExperimentRunsTableMultiColumnView2 extends React.Component {
     this.applyRowSelectionFromProps();
     this.handleColumnSizeRefit();
     this.handleLoadingOverlay();
+
+    window.addEventListener('resize', () => {
+      this.gridApi.sizeColumnsToFit();
```
Comment (Zangr) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:340]: Resize event can be busy, what do you think about debouncing 100ms here?
```
window.addEventListener('resize', _.debounce(this.gridApi.sizeColumnsToFit, 100));
```

**Review by Zangr — COMMENTED** [review]
Thank you for submitting the fix! Let's make sure we do thorough manual testing to avoid regression. Could you please test if the behavior of column change, row selection, and sorting are consistent before/after the resizing?

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js (hunk 1 above)
Comment (harupy) [reply mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:340]: Makes sense. I'll make the change

File: mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js [hunk 2]
```diff
@@ -335,6 +335,13 @@ export class ExperimentRunsTableMultiColumnView2 extends React.Component {
     this.applyRowSelectionFromProps();
     this.handleColumnSizeRefit();
     this.handleLoadingOverlay();
+
+    window.addEventListener(
+      'resize',
+      _.debounce(() => {
+        this.gridApi.sizeColumnsToFit();
+      }, 100),
```
Comment (harupy) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentRunsTableMultiColumnView2.js:343]: Wrapped `this.gridApi.sizeColumnsToFit()` with an arrow function to avoid an error caused by javasript's what-"this"-refers-to issue.

Screen Shot 2020-07-28 at 18 16 44

Screen Shot 2020-07-28 at 18 18 57

**Review by Zangr — APPROVED** [review]
LGTM
