### PR TITLE
Fix infinite fetch loop in trace detail view when num_spans metadata mismatches

### LINKED ISSUE #20595: [BUG] Infinite fetch loop in trace detail view when num_spans metadata mismatches actual span count
## Summary

When viewing trace details in the MLflow UI, an infinite fetch loop occurs if the `mlflow.trace.sizeStats.num_spans` metadata value doesn't match the actual number of spans in the trace.

## Environment

- MLflow version: 3.9.0
- Browser: Chrome
- Backend: SQLite (OSS tracking store)

## Reproduction Steps

1. Create a trace with hierarchical spans (parent-child relationships)
2. In some cases, the `num_spans` metadata may become inconsistent with the actual span count
3. Open the trace detail view in the MLflow UI
4. Observe continuous network requests to `/ajax-api/2.0/mlflow/traces/{trace_id}` or similar endpoints

## Root Cause Analysis

The issue is in the polling logic at `mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.tsx:52-73`:

```typescript
const getRefreshInterval = (data: ModelTrace | undefined) => {
  // ...
  const expected = JSON.parse(traceStats).num_spans;  // From metadata
  const actual = data?.data?.spans?.length ?? 0;       // Actual count
  return expected === actual ? false : 1000;           // Infinite loop if mismatch!
};
```

**Evidence from affected trace:**
- `mlflow.trace.sizeStats`: `{"num_spans": 33, ...}`
- Actual span count in DB: 32

This 1-span discrepancy causes the polling condition `expected !== actual` to be perpetually true.

## Trace Structure (for reference)

The affected trace has 32 spans with a hierarchical structure:
- Root span with ~8 child nodes
- Each child node has 2-6 event spans
- Total depth: 3-4 levels

## Proposed Fix

Add a safeguard to prevent infinite polling:

1. **Option A**: Add maximum retry count for polling
2. **Option B**: Add timeout after which polling stops regardless of span count mismatch
3. **Option C**: Fix backend to ensure num_spans metadata is always accurate

## Impact

- High CPU usage in browser due to continuous fetch requests
- Potential memory leaks
- Poor user experience with unresponsive UI
- Unnecessary load on MLflow server

## Related Code

- `mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.tsx`
- `mlflow/server/js/src/shared/web-shared/model-trace-explorer/hooks/useGetModelTraceInfo.tsx`

### PR DESCRIPTION
**Pull request by coldzero94**
### Related Issues/PRs

Resolve #20595

### What changes are proposed in this pull request?

Fix infinite fetch loop that occurs when viewing trace details if the `mlflow.trace.sizeStats.num_spans` metadata doesn't match the actual span count.

**Problem**: The polling logic in `useGetTrace.tsx` continued polling indefinitely after a trace reached the `OK` state, as long as the expected span count (from metadata) didn't match the actual span count. This caused:
- Continuous network requests (2000+ requests observed)
- High CPU usage in browser
- Unresponsive UI

**Root cause**: The `num_spans` metadata can become inconsistent with actual data (e.g., metadata says 33 spans, but only 32 exist in DB). Since the frontend calls the API with `allow_partial=true`, the backend's span completeness check is bypassed entirely.

**Solution**: Add a bounded retry timeout for polling when the trace is in `OK` state but span count still doesn't match:
- Continue polling for up to 60 attempts (~60s) to allow late-arriving child spans (covers OTLP BatchSpanProcessor worst case of 5s schedule delay + 30s export timeout)
- Stop polling immediately on `ERROR` state
- Reset the poll counter when navigating between traces to prevent count leaking

### How is this PR tested?

- [ ] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

Added unit tests for:
- Bounded polling stops after max retries on span count mismatch
- No polling on ERROR state
- Poll counter resets when switching between traces

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Please link the corresponding PR or explain how you plan to update it.

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Fix infinite fetch loop in trace detail view when `num_spans` metadata mismatches actual span count.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [x] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.tsx [hunk 1]
```diff
@@ -50,18 +50,22 @@ export function useGetTrace(
...
+    // state (OK or ERROR), stop polling regardless of span count.
     const traceInfo = data && isV3ModelTraceInfo(data.info) ? data.info : undefined;
 
-    // ERROR state indicates that the trace is likely finished, so stop polling
-    if (traceInfo?.state === 'ERROR') {
+    // Terminal states - stop polling
+    // Note: Previously we compared span counts even for completed traces, but this caused
+    // infinite polling loops when num_spans metadata was inconsistent with actual span count.
+    // Since the trace is already complete, no more spans will arrive, so stop polling.
+    if (traceInfo?.state === 'ERROR' || traceInfo?.state === 'OK') {
```
Comment (serena-ruan) [inline mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.tsx]: I think we shouldn't rely on 'OK' status, as previously explained in line 53-55 comments that the status could be updated while some internal spans are in-parallel uploading.
I think we could use the other option you mentioned in the issue, set a retry timeout if status is 'OK', since in such case it shouldn't take longer for all child spans to be logged.

Comment (coldzero94) [reply mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.tsx]: Thanks for the feedback! You're right that we shouldn't immediately stop polling on OK state since child spans may still be uploading in parallel.

I've updated the approach to add a bounded retry timeout: when the trace is in OK state but span count still doesn't match, we continue polling for up to 60 attempts (~60s). This covers the worst-case OTLP BatchSpanProcessor delay (5s schedule delay + 30s export timeout = 35s). The poll counter is also reset when navigating between traces to prevent count leaking.

Note: The frontend currently calls the API with allow_partial=true, so the backend's span completeness check is bypassed entirely. A more robust long-term fix could be adding a spans_complete flag to the allow_partial=true response, so the frontend can use the backend's authoritative completeness check. But that would be a separate PR.

File: mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.test.tsx [hunk 2]
```diff
@@ -92,4 +92,128 @@ describe('useGetTrace', () => {
...
+      const mockGetTrace = jest.fn<GetTraceFunction>().mockResolvedValue(traceWithOKState);
+      const { result } = renderHook(() => useGetTrace(mockGetTrace, traceWithOKState.info, true), { wrapper });
+
+      await waitFor(() => {
+        expect(result.current.isSuccess).toBe(true);
+      });
+
+      // Polling should eventually stop due to max retry count (not run forever)
+      // Wait a few seconds to verify polling occurs but is bounded
+      await new Promise((resolve) => setTimeout(resolve, 3000));
```
Comment (serena-ruan) [inline mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.test.tsx]: Could we use jest fake timers instead of real timers for testing purpose?

**Review by serena-ruan — APPROVED** [review]
LGTM! Thanks for the contribution :D Let's update tests and merge then!

File: mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.test.tsx (hunk 2 above)
Comment (coldzero94) [reply mlflow/server/js/src/shared/web-shared/genai-traces-table/hooks/useGetTrace.test.tsx]: Done! Converted all tests to use Jest fake timers. All tests pass locally.

**Comment by coldzero94** [comment]
@serena-ruan Is it done? Can you check it?

**Review by daniellok-db — APPROVED** [review]
lgtm
