### PR TITLE
fix: adjust table theme color in `Compare Run View`

### LINKED ISSUE #11592: [BUG] dark mode is not correctly applied to "model comparison" page
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

2.11.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Python version**: N/A
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When you have dark mode enabled, the "compare models" page will show very messed up, and have half light and half dark mode.

### Steps to reproduce the bug

1. Have dark mode enabled
2. Go to "models" tab
3. Select two versions of a model and click "compare"
4. Observe a strange style error

MLflow

### Code to generate data required to reproduce the bug

_No response_

### Is the console panel in DevTools showing errors relevant to the bug?

_No response_

### Does the network panel in DevTools contain failed requests relevant to the bug?

_No response_

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/Gumichocopengin8/mlflow/pull/14914?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/14914/merge
```

For Databricks, use the following command:

```
%sh
OPTIONS=$(if pip freeze | grep -q 'git+https://github.com/mlflow/mlflow.git'; then echo '--force-reinstall --no-deps'; fi)
pip install $OPTIONS git+https://github.com/mlflow/mlflow.git@refs/pull/14914/merge#subdirectory=skinny
```

</p>
</details>

### Related Issues/PRs

 close #11592

### What changes are proposed in this pull request?

Correctly apply light mode and dark mode in compare run view tables

#### Before

https://github.com/user-attachments/assets/f63bcfff-6972-4e25-a764-0ff9bc35dc22

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

#### After

https://github.com/user-attachments/assets/bc8d1353-eeba-4242-9484-45ec86422fe9

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/components/CompareRunContour.tsx [hunk 1]
```diff
@@ -17,7 +17,6 @@ import {
 } from '@databricks/design-system';
 import { getParams, getRunInfo } from '../reducers/Reducers';
 import { connect } from 'react-redux';
-import './CompareRunView.css';
```
Comment (Gumichocopengin8) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunContour.tsx:20]: not used

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx [hunk 2]
```diff
@@ -240,13 +241,14 @@ class CompareRunView extends Component<CompareRunViewProps, CompareRunViewState>
       );
     }
     return (
-      <table
+      <Table
         className="table compare-table compare-run-table"
         css={{ maxHeight: '500px' }}
+        // @ts-expect-error TS(2322): Property 'onScroll' does not exist... Remove this comment to see the full error message
```
Comment (Gumichocopengin8) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:247]: `Table` from `@databricks/design-system` doesn't support `onScroll`, so used `@ts-expect-error`

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.css
Comment (Gumichocopengin8) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.css:1]: This file is shared with `CompareModelVersionsView.tsx`, so will remove unused css after table migration.

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx (hunk 2 above)
Comment (daniellok-db) [reply mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:247]: is this just a typing issue, or is the `onScroll` handler actually ignored?

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx [hunk 3]
```diff
@@ -383,12 +387,15 @@ class CompareRunView extends Component<CompareRunViewProps, CompareRunViewState>
       },
     ];
     return rows.map(({ key, title, data }) => (
-      <tr key={key}>
-        <th scope="row" className="head-value sticky-header" css={colWidthStyle}>
+      <TableRow key={key} className="compare-table-row">
```
Comment (daniellok-db) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:390]: in the design system i believe table headers are indicated with the `isHeader` property

```suggestion
      <TableRow key={key} className="compare-table-row" isHeader>
```

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx [hunk 4]
```diff
@@ -383,12 +387,15 @@ class CompareRunView extends Component<CompareRunViewProps, CompareRunViewState>
...
+        <TableCell
```
Comment (daniellok-db) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:391]: i think there is also a `TableHeader` which is supposed to be equivalent to `th`
```suggestion
        <TableHeader
```

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx [hunk 5]
```diff
@@ -515,77 +522,80 @@ class CompareRunView extends Component<CompareRunViewProps, CompareRunViewState>
...
+                    title={r.runUuid}
+                    // @ts-expect-error TS(2322): Type '{ children: Element; title: any; color: stri... Remove this comment to see the full error message
+                    color="gray"
+                    placement="topLeft"
+                    overlayStyle={{ maxWidth: '400px' }}
+                    mouseEnterDelay={1.0}
+                  >
+                    <Link to={Routes.getRunPageRoute(r.experimentId ?? '0', r.runUuid ?? '')}>{r.runUuid}</Link>
+                  </LegacyTooltip>
+                </TableCell>
```
Comment (daniellok-db) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:553]: same comments here about `<TableRow isHeader>` and `<TableHeader>`

**Review by daniellok-db — APPROVED** [review]
this looks great, left some nits, will merge after they're addressed!

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx (hunk 5 above)
Comment (daniellok-db) [reply mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:553]: ah i see, let's leave it as it is then
