### PR TITLE
Fix DSPy prompt display

### LINKED ISSUE #17940: [BUG] MLFLOW UI not render UI for prompt
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

I'm using the latest version of mlflow(3.4.0).

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

The New line is not rendered in the prompt tracing UI

Image

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow model serving, deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/prompt`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/uiux`: Front-end, user experience, plotting
- [ ] `area/docs`: MLflow documentation pages

### PR DESCRIPTION
**Pull request by B-Step62**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/B-Step62/mlflow/pull/17988?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17988/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17988/merge#subdirectory=libs/skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/17988/merge
```

</p>
</details>

### What changes are proposed in this pull request?

Fix https://github.com/mlflow/mlflow/issues/17940

DSPy prompt is not markdown, but the chat UI tries to render it as markdown. This causes a problem in rendering new line, because single new line `\n` doesn't create line break in markdown. For example,

```
[[ ## library ## ]]
mlflow
```

is rendered as 
```
[[ ## library ## ]] mlflow
```

This PR applies a fix to replace single new line `\n` to double `\n\n`, when parsing chat-style message from DSPy LLM span.

Note that non-markdown prompt is not only the case for DSPy, e.g., some LLM prefer xml format. However, it is challenging to accurately determine if the input is markdown or not.

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

**Before**
Screenshot 2025-09-27 at 21 37 58

**After**
Screenshot 2025-09-27 at 21 37 43

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Fix chat UI new line rendering issue for DSPy prompt.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [x] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by harupy** [comment]
/review

---
🚀 [Review workflow started](https://github.com/mlflow/mlflow/actions/runs/18087310568)

File: mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts [hunk 1]
```diff
@@ -19,10 +25,15 @@ export const normalizeDspyChatOutput = (obj: unknown): ModelTraceChatMessage[] |
...
     return message && [message];
   }
 
   return null;
 };
+
+// Markdown treats single newlines as spaces. For DSPy prompts that are plain text
+// we convert single newlines into hard line breaks while preserving paragraphs.
+const toMarkdownWithHardBreaks = (text: string) =>
+  text.replace(/\r\n/g, '\n').replace(/(^|[^\n])\n(?!\n)/g, (_m, p1) => `${p1}  \n`);
```
Comment (harupy) [inline mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts:42]: can we add a minimum input/output example like `foo\nbar` -> `foo  \nbar` or `foo\n\nbar` -> `foo\n\nbar`?

**Review by harupy — APPROVED** [review]
LGTM once https://github.com/mlflow/mlflow/pull/17988/files#r2386821644 is addressed!

File: mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts [hunk 2]
```diff
@@ -19,10 +25,15 @@ export const normalizeDspyChatOutput = (obj: unknown): ModelTraceChatMessage[] |
...
+    const content = toMarkdownWithHardBreaks(obj.join('\n'));
     const message = prettyPrintChatMessage({ type: 'message', content, role: 'assistant' });
     return message && [message];
   }
 
   return null;
 };
+
+// Markdown treats single newlines as spaces. For DSPy prompts that are plain text
+// we convert single newlines into hard line breaks while preserving paragraphs.
```
Comment (B-Step62) [inline mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts:37]:
```suggestion
// we convert single newlines into hard line breaks while preserving paragraphs.
// Only the single line break will bre updated, for example, 
// - "foo\nbar" -> "foo\n\nbar" (a new line inserted)
// - "foo\n\nbar" -> "foo\n\nbar" (no change)
```

**Comment by harupy** [comment]
/review

---
🚀 [Review workflow started](https://github.com/mlflow/mlflow/actions/runs/18090347704)

File: mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts [hunk 3]
```diff
@@ -19,10 +25,18 @@ export const normalizeDspyChatOutput = (obj: unknown): ModelTraceChatMessage[] |
...
+// Only the single line break will bre updated, for example, 
+// - "foo\nbar" -> "foo\n\nbar" (a new line inserted)
```
Comment (harupy) [inline mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts]: Is this example correct?

Comment (B-Step62) [reply mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts]: ah nope, sorry was multi-tasking:(

File: mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts [hunk 4]
```diff
@@ -19,10 +25,18 @@ export const normalizeDspyChatOutput = (obj: unknown): ModelTraceChatMessage[] |
...
   }
 
   return null;
 };
+
+// Markdown treats single newlines as spaces. For DSPy prompts that are plain text
+// we convert single newlines into hard line breaks while preserving paragraphs.
+// Only the single line break will bre updated, for example,
+// - "foo\nbar" -> "foo  \nbar" (a new line inserted)
+// - "foo\n\nbar" -> "foo\n\nbar" (no change)
```
Comment (harupy) [inline mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts]:
```suggestion
// Only the single line break will be updated, for example,
// - "foo\nbar" -> "foo  \nbar" (two spaces inserted before \n)
// - "foo\n\nbar" -> "foo\n\nbar" (no change)
```

nit: `a new line inserted` sounds like `another new line inserted`

File: mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts [hunk 5]
```diff
@@ -8,7 +8,13 @@ export const normalizeDspyChatInput = (obj: unknown): ModelTraceChatMessage[] |
   if (has(obj, 'messages') && isArray((obj as any).messages)) {
     const messages = (obj as any).messages;
     return messages
-      .map((msg: any) => prettyPrintChatMessage({ type: 'message', content: msg.content, role: msg.role }))
+      .map((msg: any) =>
+        prettyPrintChatMessage({
+          type: 'message',
+          content: isString(msg.content) ? toMarkdownWithHardBreaks(msg.content) : msg.content,
```
Comment (TomeHirata) [inline mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts:14]: what type is expected if msg.content is not a string?

Comment (B-Step62) [reply mlflow/server/js/src/shared/web-shared/model-trace-explorer/chat-utils/dspy.ts:14]: Anything that the DSPy's message can include. Not sure if it support non-string, but it's not guaranteed?
