### PR TITLE
Fix dark mode CSS not consistently applied in compare runs page

### LINKED ISSUE #22210: [BUG] Dark mode CSS not consistently applied in compare runs page
> [!WARNING]
> Before submitting a PR, please make sure that:
> - A maintainer has triaged this issue and applied the `ready` label
> - This issue has no assignee
> - No duplicate PR exists
>
> PRs not meeting these requirements may be automatically closed.

### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: N/A
- Tracking server: 3.10.1 (reproduces on `master branch)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 43
- **Python version**:  3.12

### Describe the problem

The dark mode theme is inconsistent on the compare runs table where some stay "light" while others are "dark":
Image

### Tracking information

_No response_

### Code to reproduce issue

N/A

### Stack trace

N/A

### Other info / logs

N/A

### What component(s) does this bug affect?

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow model serving, deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/prompt`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting
- [ ] `area/docs`: MLflow documentation pages

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
### Related Issues/PRs

Closes #22210

### What changes are proposed in this pull request?

Dark mode theme colors were not applied to compare run tables and Plotly charts on the compare runs page. Table headers, borders, diff-row highlights, and hover states used hardcoded light-mode colors in `CompareRunView.css`, while Plotly charts rendered with a default white background.

**Tables fix** (`CompareRunView.css`, `CompareRunView.tsx`, `CompareModelVersionsView.tsx`):
- Replace hardcoded colors in `CompareRunView.css` with CSS custom properties (`var(--mlflow-compare-*, <fallback>)`) that retain the original light-mode values as fallbacks.
- Add a `CompareRunTable` functional component in `CompareRunView.tsx` (with `forwardRef`) that uses `useDesignSystemTheme()` to set the CSS custom properties via the `style` prop — matching the existing `CompareTable` pattern in `CompareModelVersionsView.tsx`.
- Set the same CSS custom properties on the existing `CompareTable` component in `CompareModelVersionsView.tsx`, which imports and shares `CompareRunView.css`.

**Charts fix** (`LazyPlot.tsx`):
- Make `LazyPlot` theme-aware by injecting `paper_bgcolor: 'transparent'`, `plot_bgcolor: 'transparent'`, `font.color`, `gridcolor`, and `zerolinecolor` from theme tokens into the Plotly layout. This fixes all four chart types (Parallel Coordinates, Scatter, Box, Contour) at once.

Screenshot 2026-04-01 at 12 01 32 PM
Screenshot 2026-04-01 at 12 01 54 PM
Screenshot 2026-04-01 at 12 02 07 PM
Screenshot 2026-04-01 at 12 02 21 PM

https://github.com/user-attachments/assets/ca019374-babb-4712-850c-37db7b6d02ae

### How is this PR tested?

- [ ] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests

Verified in the MLflow dev server with dark mode enabled that:
- Compare runs table headers, borders, diff highlights, and hover states use dark-mode-appropriate colors
- Plotly charts (Parallel Coordinates, Scatter, Box, Contour) render with transparent backgrounds and readable text/gridlines in dark mode
- Light mode appearance is unchanged (CSS custom properties fall back to original values)

### Does this PR require documentation update?

- [x] No.

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.

#### Is this a user-facing change?

- [x] Yes. Fix dark mode CSS not being consistently applied on the compare runs page — table headers, borders, diff-row highlights, and Plotly chart backgrounds now respect dark mode.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

- [x] This PR can wait for the next minor release

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
Update the screenshots and screen recording for the hover styles. I have self-reviewed the code and manually verified it. Thanks for any reviews!

File: mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx [hunk 1]
```diff
@@ -8,7 +8,15 @@
...
-import { Spacer, Switch, LegacyTabs, LegacyTooltip, Tooltip, Typography } from '@databricks/design-system';
+import {
+  Spacer,
+  Switch,
+  LegacyTabs,
+  LegacyTooltip,
+  Tooltip,
+  Typography,
+  useDesignSystemTheme,
+} from '@databricks/design-system';
```
Comment (TomeHirata) [inline mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:19]: Can we use Table component from the design system instead of manually configuring styles?

Comment (DaoDaoNoCode) [reply mlflow/server/js/src/experiment-tracking/components/CompareRunView.tsx:19]: Hi @TomeHirata, thanks for the review! I looked into using the Table component from the design system, but it's designed to work with `@tanstack/react-table` (column definitions, data arrays, hook-based rendering), which is quite different from how `CompareRunView` builds its tables today (manually rendered rows with diff highlighting, cross-table scroll sync, sticky headers, etc.).

Migrating to the DS Table would essentially require rewriting the table rendering logic and converting this class component to a functional component, which means it's a bigger refactor on top of this dark mode fix. The CSS custom property approach here is consistent with how `CompareModelVersionsView` already handles theming (its `CompareTable` component does the same thing).

That said, I'm happy to take on the migration in this PR if you'd prefer, just let me know!

**Review by TomeHirata — APPROVED** [review]
LGTM
