### PR TITLE
Fix tag key validation UI contradiction

### LINKED ISSUE #21075: [BUG] Tag validation contradicts itself in UI
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

- Client: 3.9.0
- Tracking server: 3.9.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **Python version**: 3.12.12

### Describe the problem

In the screenshot below the UI tells me the a tag's key may contain "/".

Image

When I do use a "/", it tells me it cannot use that character:

Image

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
REPLACE_ME
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow model serving, deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/prompt`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting
- [ ] `area/docs`: MLflow documentation pages

### PR DESCRIPTION
**Pull request by KaushalVachhani**
- Add shared tagKeyValidation.ts aligned with backend (allow /, ., -, :, space; path rules)
- Update Add New Tag modal and TagSelectDropdown to use it and show backend-consistent message
- Add unit tests for isValidTagKey

Before:
Before

After:
After
After-2

### Related Issues/PRs

Fixes #21075

### How is this PR tested?

- [ ] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Please link the corresponding PR or explain how you plan to update it.

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/server/js/src/common/utils/tagKeyValidation.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ * Mirrors backend _validate_tag_name + path_not_unique logic.
+ */
+export function isValidTagKey(key: string): boolean {
+  if (key === '') return true;
+  if (!TAG_KEY_ALLOWED_CHARS_REGEX.test(key)) return false;
+  // path_not_unique: no leading slash, not ".", not "..", no path traversal
+  if (key.startsWith('/')) return false;
+  if (key === '.') return false;
+  if (key.startsWith('..')) return false;
+  if (key.includes('/.') || key.includes('/..') || key.includes('//')) return false;
```
Comment (daniellok-db) [inline mlflow/server/js/src/common/utils/tagKeyValidation.ts]: it looks like this validation is a little too strict as the backend does accept things like `test/.test`. what happens if we remove this line? can we let the backend return us the error message and display it?

**Review by daniellok-db — COMMENTED** [review]
overall it looks good but left one question about relaxing the validation condition from the frontend for some of the more complex cases and just letting the backend handle it.

**Comment by KaushalVachhani** [comment]
> overall it looks good but left one question about relaxing the validation condition from the frontend for some of the more complex cases and just letting the backend handle it.

Done @daniellok-db. I removed the path traversal check so keys like test/.test are no longer rejected on the frontend. The UI already shows backend errors when tag save fails (useEditKeyValueTagsModal uses setErrorMessage from the API response), so if the backend rejects a key we now display its error message in the modal. Docstring and tests are updated accordingly.

**Review by daniellok-db — APPROVED** [review]
lg! thanks for the fix
