### PR TITLE
Bypassing conda when running R scripts (by setting env vars)

### LINKED ISSUE #1649: Problem running R script with --no-conda
### System information
- **OS Platform and Distribution**: Ubuntu 18.10
- **MLflow version**: 1.1.0
- **Python version**: 3.6.8 

### Describe the problem
I'm trying to use mlflow using `--no-conda` (it's not installed on my system). It works fine when I run python code but when I try to run an R script I get: "Error: Unable to find conda binary. Is Anaconda installed?"

That error is raised by `mlflow:::mlflow_conda_bin()` when calling `reticulate::conda_python()`. I would expect that using `--no-conda` would skip that step.

### PR DESCRIPTION
**Pull request by spadarian**
(closes: #1649)

## What changes are proposed in this pull request?
 
- The R package now looks for `--no-conda` in the argument list to avoid using `reticulate::conda_python()`, which fails when conda is not available (#1649)
- Two extra arguments should be provided when using `--no-conda`: `--python=<python_path>` and `--mlflow=<mlflow_path>`

Example:
```bash
Rscript train.R --no-conda --python=`which python` --mlflow=`which mlflow`
```

- When running an R script using `mlflow run --no-conda`, the entry point in the _MLproject_ file doesn't need to include all the new arguments. They are automatically added when `mlflow run . --no-conda` (assuming both are available in `PATH`).

```yaml
entry_points:
  main:
    command: "Rscript train.R"
```
- Optionally, the user can specify custom paths to Python and MLflow in the _MLproject_ file:

```yaml
entry_points:
  main:
    command: "Rscript train.R --python=/path/to/my/python --mlflow=/path/to/my/mlflow"
```

 
## How is this patch tested?
 
It passed all the tests in Travis
 
### Is this a user-facing change? 

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.
 
There are new arguments available for the user when running R scripst and conda is not installed.
 
### What component(s) does this PR affect?
 
- [ ] UI
- [ ] CLI 
- [ ] API 
- [ ] REST-API 
- [ ] Examples 
- [ ] Docs
- [ ] Tracking
- [ ] Projects 
- [ ] Artifacts 
- [ ] Models 
- [ ] Scoring 
- [ ] Serving
- [x] R
- [ ] Java
- [x] Python

### How should the PR be classified in the release notes? Choose one:
 
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/R/mlflow/R/cli.R [hunk 1]
```diff
@@ -24,11 +24,19 @@ mlflow_cli <- function(...,
...
-  ), env)
+
+  if (!is.null(python_conda_home())) {
+    env <- modifyList(list(
+      PATH = paste(python, Sys.getenv("PATH"), sep = ":"),
+      MLFLOW_CONDA_HOME = python_conda_home(),
+      MLFLOW_TRACKING_URI = mlflow_get_tracking_uri()
+    ), env)
+  } else {
+    env <- modifyList(list(
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/cli.R]: I believe that in case the python binary is not the default python you still need to put it at the start of the PATH.

File: mlflow/R/mlflow/R/python.R [hunk 2]
```diff
@@ -1,13 +1,34 @@
...
+    if (is.null(path)) {
+      stop(paste("When using --no-conda option you also need to provide path to",
+                 "Python and MLflow using --python=<path> and --mlflow=<path>"))
+    }
+  } else {
+    conda <- mlflow_conda_bin()
+    envs <- conda_list(conda = conda)
+    mlflow_env <- envs[envs$name == mlflow_conda_env_name(), ]
+    if (nrow(mlflow_env) == 0) {
+      stop("MLflow not configured, please run install_mlflow().")
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/python.R]: Update the error message to include the option of setting python binary explicitly.

**Review by tomasatdatabricks — CHANGES_REQUESTED** [review]
Hi @spadarian, thanks for the PR!

It looks good overall. I have a few requests:

1. Can we use environment variable (e.g. MLFLOW_PYTHON_BIN) instead of command line arg to specify python binary explicitly? I think environment variable would work better in this case since users could then set it just once.
2. I think that the logic for obtaining python binary can be simplified to use the environment variable if set and default to the current logic of calling into conda. This change should be done only in one place - get_python_bin.
3. We should be careful about setting the PATH variable. If the python bin is not the default one, we might need to explicitly add it to the front of the PATH to make sure any subsequent python processes use the right python with the right environment.
4. Some tests would be nice.

**Comment by spadarian** [comment]
The simplest way to make it work is by using 2 env variables MLFLOW_PYTHON_BIN and MLFLOW_BIN.
- MLFLOW_PYTHON_BIN is checked by `get_python_bin()`.
- MLFLOW_BIN is checked by `python_mlflow_bin()`. If it is not set, it assumes that `mlflow` is in the same dir as MLFLOW_PYTHON_BIN.
- If both bins exist, `python_conda_home()` returns `""`

Those are the only 3 changes needed.

Now, I need to let the user know that they can set those variables. If no env variables are set, the exception is raised by `get_python_bin()` when executing `mlflow_conda_bin()`. Should I try catching that (with `try`) and return the same message ("Error: Unable to find conda binary. Is Anaconda installed?") plus a message like "If you are not using conda, you can set the environmental variable MLFLOW_PYTHON_BIN to the path of your python executable.".

**Comment by spadarian** [comment]
Have a look at https://github.com/spadarian/mlflow/tree/fix_r_no_conda2
If you are happy with those changes, I can merge that branch into this one or create a new PR.

**Comment by tomasatdatabricks** [comment]
Hi @spadarian.

Looks good, thanks for adding the tests! Please merge it here. I have a few comments still but it would be easier to add those to the PR. 

Just briefly: Why do you want to use MLFLOW_BIN variable? I think that one should always point to dirname(mlflow_python_bin())/mlflow since the python environment must have mlflow installed. I think it would be simpler that way.

**Comment by spadarian** [comment]
Well, in my system, they are not in the same directory. If I create a venv,
they will, but it's not always the case.

If the user only sets MLFLOW_PYTHON_BIN, it will look for mlflow in the
same directory. If they are not in the same directory, it will ask the user
to set MLFLOW_BIN. I think that is fine.

**Comment by tomasatdatabricks** [comment]
Ok that makes sense!

File: mlflow/R/mlflow/R/python.R [hunk 3]
```diff
@@ -1,6 +1,10 @@
 # Computes path to Python executable within conda environment created for the MLflow R package
 #' @importFrom reticulate conda_list
 get_python_bin <- function() {
+  in_env <- Sys.getenv("MLFLOW_PYTHON_BIN")
+  if (file.exists(in_env)) {
+    return(in_env)
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/python.R]: If the environment variable is set we should always use it. If the file does not exist we should throw an error instead of falling back to behavior without the env var.

File: mlflow/R/mlflow/R/python.R [hunk 4]
```diff
@@ -23,13 +27,26 @@ python_bin <- function() {
 # Returns path to MLflow CLI, assumed to be in the same bin/ directory as the
 # Python executable
 python_mlflow_bin <- function() {
+  in_env <- Sys.getenv("MLFLOW_BIN")
+  if (file.exists(in_env)) {
+    return(in_env)
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/python.R]: Same as above, if the environment variable is set we should use it.

File: mlflow/R/mlflow/R/python.R [hunk 5]
```diff
@@ -23,13 +27,26 @@ python_bin <- function() {
...
+  }
   python_bin_dir <- dirname(python_bin())
-  file.path(python_bin_dir, "mlflow")
+  path <- file.path(python_bin_dir, "mlflow")
+  if (!file.exists(path) && file.exists(Sys.getenv("MLFLOW_PYTHON_BIN"))) {
+    stop("Mlflow executable does not seem to be in the same directory than Python.\n",
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/python.R]: nit: same directory as Python. We could also just say "Could not find MLflow CLI executable, please set ..."

File: mlflow/R/mlflow/R/python.R [hunk 6]
```diff
@@ -23,13 +27,26 @@ python_bin <- function() {
...
+         )
+  }
+  path
 }
 
 # Return path to conda home directory, such that the `conda` executable can be found
 # under conda_home/bin/
 #' @importFrom reticulate conda_binary
 python_conda_home <- function() {
+  if (file.exists(Sys.getenv("MLFLOW_PYTHON_BIN")) && file.exists(python_mlflow_bin())) {
```
Comment (tomasatdatabricks) [inline mlflow/R/mlflow/R/python.R]: Can we call mlflow_conda_bin() in Try/Catch block and return NULL on exception? The existence of conda does not depend on if user selected other python binary.

**Review by tomasatdatabricks — COMMENTED** [review]
Thanks for the updates! 

I left a few minor comments.

**Review by tomasatdatabricks — COMMENTED** [review]
Thanks for the updates! I left 2 minor comments.

**Comment by spadarian** [comment]
I think the new commit should do what you want.

**Review by tomasatdatabricks — APPROVED** [review]
Looks great, thank you @spadarian!
