### PR TITLE
Use sampling data for run comparison

### LINKED ISSUE #5779: [BUG] Metric plot slow for many data points
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No, this concerns the UI.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 1.25.1
- **Python version**: 3.8.10
- **Exact command to reproduce**: `mlflow ui --backend-store-uri "sqlite:///mlruns.db"`

### Describe the problem
Currently, in the MLFlow tracking UI metrics plot, when plotting around 100k points, the plot becomes unusably slow.

It appears like no simplification / decimation / subsampling strategy is used and all data points are simply rendered.

As I prefer to log metrics at all training steps, this is very problematic. Tensorboard, for example, subsamples the data points at the server-side, making plotting fast. This is configured via a [CLI argument](https://github.com/tensorflow/tensorboard/blob/348af4cf9564b8217750e8d84e0b2b89555be62c/tensorboard/data/server/cli.rs#L129).

The issue appears to lie in the rendering part, as the large JSON files containing all the metrics loads sufficiently fast.

Possible solutions:
- Subsample the data points server-side
- Subsample the data points client-side
- Use an adaptive method on the client side, such as https://github.com/predict-idlab/plotly-resampler 

### Tracking information
```
MLflow version: 1.25.1
Tracking URI: sqlite:///mlruns.db
```
```
mlflow ui --backend-store-uri "sqlite:///mlruns.db"
```

### Code to reproduce issue
Any plot with around 100k points.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by lkuo**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/lkuo/mlflow/pull/17645?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17645/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17645/merge#subdirectory=libs/skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/17645/merge
```

</p>
</details>

### Related Issues/PRs

Resolve #5779

### What changes are proposed in this pull request?

- Use sampling API `get-history-bulk-interval` to get metrics for charts.
- Fixed a bug in `MetricsReducer` causing `isfresh` state not properly set when multiple metrics are selected
- Set the full metrics polling interval to 2x sampling data polling interval
- Removed error messages when > 10k metrics

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

- the compare runs chart uses sample metrics api, which by default loads 320 data points
- compare run page now fetches data even if there are more than 100k data points (will still show a warning about page performance)
- slow down the full metrics poll rate to sample metrics polling rate * 2
- call metrics history api before export to CSV

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

The compare runs page chart looks nicer now for runs with large number of data points by using the sample data.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [x] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

**Comment by lkuo** [comment]
@daniellok-db Hi Daniel, could you please take a look at this PR? Thanks.

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 1]
```diff
@@ -60,11 +83,16 @@ type OwnMetricsPlotPanelProps = {
...
+  runNames?: string[];
+  runInfos?: any[];
 };
 
 type MetricsPlotPanelState = any;
 
-type MetricsPlotPanelProps = OwnMetricsPlotPanelProps & typeof MetricsPlotPanel.defaultProps;
+type MetricsPlotPanelProps = OwnMetricsPlotPanelProps & {
+  containsInfinities: boolean;
+};
```
Comment (BriannaRoskind) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: nit: `OwnMetricsPlotPanelProps` appears to already have `containsInfinities`, so this may be an accidental change as a result of rebasing.

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 2]
```diff
@@ -680,7 +729,7 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
           handleShowPointChange={this.handleShowPointChange}
           handleYAxisLogScaleChange={this.handleYAxisLogScaleChange}
           handleLineSmoothChange={this.handleLineSmoothChange}
-          chartType={chartType}
+          chartType={CHART_TYPE_LINE}
```
Comment (BriannaRoskind) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: Can you confirm whether it is an improved behavior to hardcoding this as `CHART_TYPE_LINE` rather than relying on `predictChartType()`, which can also return `CHART_TYPE_BAR` when ["every metric has exactly 1 metric history"](https://github.com/mlflow/mlflow/blob/bccb79d1d863f2eea9f40aa5ee2631a9672bc33c/mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx#L206). 

`predictChartType()` is still defined (line 227) in this file and should be removed if it is really not intended for use (it is only used in this file).

**Comment by TomeHirata** [comment]
Can you fix the type check error?

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 3]
```diff
@@ -619,53 +637,84 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
-      this.setState({ popoverVisible: false });
+  // New chart system methods
+  getCardChartConfig = () => {
+    const { metricKey } = this.props;
+    const urlState = this.getUrlState();
+    const config = new RunsChartsLineCardConfig(false, getUUID());
+    const selectedMetricKeys =
+      urlState.selectedMetricKeys && urlState.selectedMetricKeys.length > 0 ? urlState.selectedMetricKeys : [metricKey];
+
+    Object.assign(config, {
```
Comment (TomeHirata) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: nit: Can we use spread operator instead of mutating `config`?

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 4]
```diff
@@ -619,53 +637,84 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
+          images: {},
+          hidden: false,
+          color: undefined,
+          displayName: runNames?.[index] || runDisplayNames?.[index] || runUuid,
+        } as RunsChartsRunData),
+    );
+  };
+
+  getGlobalLineChartConfig = () => {
+    const urlState = this.getUrlState();
```
Comment (TomeHirata) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]:
```suggestion
    const { lineSmoothness, selectedXAxis } = this.getUrlState();
```

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 5]
```diff
@@ -532,8 +534,24 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
-  handleDownloadCsv = () => {
-    const csv = convertMetricsToCsv(this.props.metricsWithRunInfoAndHistory);
+  handleDownloadCsv = async () => {
+    if (!this.state['loading']) {
+      const state = this.getUrlState();
+      const selectedMetricKeys = state.selectedMetricKeys || [];
+      await this.loadMetricHistory(this.props.runUuids, selectedMetricKeys);
+    } else {
+      // Wait for current loading to finish
+      while (this.state['loading']) {
```
Comment (hubertzub-db) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: please use promises/callbacks code instead of looped setTimeout

File: mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts [hunk 6]
```diff
@@ -60,12 +60,9 @@ export const sampledMetricsByRunUuid = (
...
       } else if (updatedState[runUuid][key][rangeKey] && isRefreshing) {
-        return {
-          ...state,
-          [runUuid]: {
-            ...state[runUuid],
-            [key]: { ...state[runUuid][key], [rangeKey]: { ...state[runUuid][key][rangeKey], refreshing: true } },
-          },
+        updatedState[runUuid][key][rangeKey] = {
+          ...updatedState[runUuid][key][rangeKey],
+          refreshing: true,
```
Comment (hubertzub-db) [inline mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts:65]: redux expects updates using immutable objects, what's the reason for changing this to mutable update?

Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts:65]: This change does not mutate exiting state. The updated state is created at [line 36](https://github.com/mlflow/mlflow/blob/73fa849c306b624a34c0a29b9c7e46bf25694937/mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts#L36) and returned at [line 69](https://github.com/mlflow/mlflow/blob/73fa849c306b624a34c0a29b9c7e46bf25694937/mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts#L69), matching the existing pattern of other branches in this section.

This is a bug fix for only the first run's `refreshing` state is updated. `GET_SAMPLED_METRIC_HISTORY_API_BULK` accepts multiple run ids, returning early causes only the first run's state is updated while the rest remains the same. causing redundant REST call, see [here](https://github.com/mlflow/mlflow/blob/73fa849c306b624a34c0a29b9c7e46bf25694937/mlflow/server/js/src/experiment-tracking/sdk/SampledMetricHistoryService.ts#L57-L74).

Comment (hubertzub-db) [reply mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts:65]: well it definitely mutates the nested state instead of recreating it; however, it's not that important as there are no consumers subscribed to the nested state specifically 🙂 
Does this particular change help fixing the bug? If so, it might be worth to visit consumer code as well 🤔

Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts:65]: Sorry for the confusion. But yes, with this change, all metrics' `refreshing` state gets updated. now we clean `get-metric-history-bulk-interval` call per selected metric.

could you explain what do you mean by consumer code?

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 5 above)
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: [done](https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4L523)

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 4 above)
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: [done](https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4R547)

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 3 above)
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: [done](https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4R496)

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 7]
```diff
@@ -532,8 +534,24 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
+        await new Promise((resolve) => setTimeout(resolve, 100));
+      }
```
[the remark this answers is not in the document]
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: [done](https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4L523)

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: [done](https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4R453)

[the remark this answers is not in the document]
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: https://github.com/mlflow/mlflow/pull/17645/files#diff-fb719875dec52f7d35d741d4d6273c6e776e5fc40fb4180ce790655ec40bc2c4R453

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 1 above)
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: reverted

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx (hunk 2 above)
Comment (lkuo) [reply mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx]: Now uses `RunsChartsCard` following existing pattern in `RunsCompare` component

**Comment by B-Step62** [comment]
@lkuo Could you fix JS tests? It fails at `yarn type-check`.

**Comment by B-Step62** [comment]
@TomeHirata @hubertzub-db Could you guys do another round of review? Hoping to merge this in by 3.5 RC.

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 8]
```diff
@@ -60,6 +89,9 @@ type OwnMetricsPlotPanelProps = {
   navigate: NavigateFunction;
   runDisplayNames: string[];
   containsInfinities: boolean;
+  // Additional props for new chart system
+  runNames?: string[];
+  runInfos?: any[];
```
Comment (hubertzub-db) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx:94]: tip: you can probably use `RunInfoEntity` type from `mlflow/server/js/src/experiment-tracking/types.ts`

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 9]
```diff
@@ -73,50 +105,27 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
     super(props);
     this.state = {
       historyRequestIds: [],
-      popoverVisible: false,
-      popoverX: 0,
-      popoverY: 0,
-      popoverRunItems: [],
       focused: true,
       loading: false,
+      fullScreenChart: undefined as
```
Comment (hubertzub-db) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx:118]: nit: should we explicitly define component's state TS type instead of using `as` here?

File: mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx [hunk 10]
```diff
@@ -462,145 +448,23 @@ export class MetricsPlotPanel extends React.Component<MetricsPlotPanelProps, Met
...
-      lastLinearYAxisRange = [];
-      const axisType = state.layout && state.layout.yaxis && state.layout.yaxis.type === 'log' ? 'log' : 'linear';
-      newYAxis.autorange = true;
-      newYAxis.type = axisType;
+  handleDownloadCsv = async () => {
+    const { loading } = this.state;
+    if (!loading) {
+      const state = this.getUrlState();
+      const selectedMetricKeys = state.selectedMetricKeys || [];
+      this.loadMetricHistoryPromise = this.loadMetricHistory(this.props.runUuids, selectedMetricKeys);
```
Comment (hubertzub-db) [inline mlflow/server/js/src/experiment-tracking/components/MetricsPlotPanel.tsx:456]: nit: isn't `loadMetricHistory` setting this instance field anyway?
shouldn't we just `await this.loadMetricHistory(this.props.runUuids, selectedMetricKeys);`?

File: mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts (hunk 6 above)
Comment (hubertzub-db) [reply mlflow/server/js/src/experiment-tracking/reducers/SampledMetricsReducer.ts:65]: Ah by "consumer code" I meant "place in the code where this state is being read" 🙂 
Ok, I got it now - instead of allowing all runs to be updated in the loop, we returned early. Fix makes perfect sense!

**Review by hubertzub-db — APPROVED** [review]

**Review by TomeHirata — APPROVED** [review]
LGTM!
