### PR TITLE
Do not notify user in UI on failed artifact fetch

### LINKED ISSUE #6984: [BUG] Model version UI page requires MLmodel at top level of artifact directory
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.28.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: server is a docker image based on `python:3.8.10`, browser is Google Chrome Version 105.0.5195.125 (Official Build) (arm64) running on macOS Monterey v12.3.1 (M1 chip)
- **Python version**: 3.8.10
- **yarn version, if running the dev UI**: N/A, not running dev UI

### Describe the problem

After upgrading from version 1.26.1 to version 1.28.0, each time we load the model version UI page (/models/.../versions/...), we see the following error at the top of the page:
```
INTERNAL_ERROR: The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': "ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')"}
```
It appears that this is because an `MLmodel` file is required to be at the top level of the directory, but this is not the case for any of our models. Some of our models have only custom artifacts, but even the ones that were packaged by MLflow have the MLmodel file within a `model` directory and not at the top level.

I tried downgrading back to v1.26.1, and the networking error described in the console below is still present, but for some reason the error is not displayed on the UI (which is fine for us, this error does not seem to be affecting anything in the UI). I also tried digging into the MLflow code around this call and everything I've found has not been touched in years. 

### Steps to reproduce the bug

1. Run a v1.28.0 MLflow server with an s3 artifact repo (we were using mysql for model registry and tracking stores, but not sure if that's relevant to this issue)
2. Create a run with no artifacts (you can use the code block below)
3. Navigate to the model version page for your created model `<mlflow_base_url>/#/models/<model_name>/versions/<model_version>`
4. Observe the error in the UI

### Code to generate data required to reproduce the bug

```py
import mlflow
from mlflow.tracking import MlflowClient

tracking_uri = '<your-tracking-uri>'

client = MlflowClient(tracking_uri)
mlflow.set_experiment(experiment_id='<your-experiment-id>')

with mlflow.start_run() as run:
    artifact_uri = run.info.artifact_uri
    run_id = run.info.run_id

model_name = '<your-model-name>'
client.create_registered_model(model_name)
client.create_model_version(model_name, artifact_uri, run_id)
```

### Is the console panel in DevTools showing errors relevant to the bug?

```
GET https://<url>/model-versions/get-artifact?path=MLmodel&name=<model_name>&version=<version_number> 500

"{"error_code": "INTERNAL_ERROR", "message": "The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': \"ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')\"}"}"
```

### Does the network panel in DevTools contain failed requests relevant to the bug?

# Headers:
## General:
Request URL: https://<url>/model-versions/get-artifact?path=MLmodel&name=<model_name>&version=1
Request Method: GET
Status Code: 500 
Remote Address: <ip>
Referrer Policy: strict-origin-when-cross-origin

## Response Headers:
content-length: 308
content-type: application/json
date: Wed, 05 Oct 2022 22:59:30 GMT
strict-transport-security: max-age=15724800; includeSubDomains

## Request Headers:
:authority: <url>
:method: GET
:path: /model-versions/get-artifact?path=MLmodel&name=<model_name>&version=1
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
referer: <url>
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

# Payload
path: MLmodel
name: <model_name>
version: 1

# Response
{"error_code": "INTERNAL_ERROR", "message": "The following failures occurred while downloading one or more artifacts from s3://<path>/artifacts: {'MLmodel': \"ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')\"}"}

### PR DESCRIPTION
**Pull request by kevingreer**
Signed-off-by: Kevin Greer kevinegreer@gmail.com

## Related Issues/PRs

Resolve #6984 

## What changes are proposed in this pull request?

If the UI fails to load an artifact, do not notify the user but instead just display the error in the console.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

Run the MLflow UI (follow the steps in the [contributing guide](https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md#javascript-and-ui)). I used a fresh sqlite DB and used the Python SDK to create a single run with no artifacts, and then a model and model version.

```py
import mlflow
from mlflow.tracking import MlflowClient

tracking_uri = '<your-tracking-uri>'

client = MlflowClient(tracking_uri)
mlflow.set_experiment(experiment_id='<your-experiment-id>')

with mlflow.start_run() as run:
    artifact_uri = run.info.artifact_uri
    run_id = run.info.run_id

model_name = '<your-model-name>'
client.create_registered_model(model_name)
client.create_model_version(model_name, artifact_uri, run_id)
```

Before this change there was an error displayed in the model version page.

https://user-images.githubusercontent.com/7669871/194678161-2042bd8f-6773-4b0f-bb5a-ffdc10666a79.mov

After the error is still visible in the browser console and the server console, but no error is displayed in the web page

https://user-images.githubusercontent.com/7669871/194678178-fb6817b4-8cce-4275-90e0-4102d377ab7a.mov

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly by following the steps below.

1. Click the `Details` link on the `Preview docs` check.
2. Find the changed pages / sections and make sure they render correctly.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

The UI will no longer display an error in the model version page if the version does not have an MLmodel file at the top level of its artifact directory.

### What component(s), interfaces, languages, and integrations does this PR affect?
Components
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>
### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/common/utils/ArtifactUtils.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ export function getArtifactContent(artifactLocation, isBinary = false) {
         fileReader.readAsText(blob);
       }
     } catch (error) {
-      Utils.logErrorAndNotifyUser(error);
+      console.error(error);
```
Comment (dbczumar) [inline mlflow/server/js/src/common/utils/ArtifactUtils.js:40]: @kevingreer Looks like we're all set once we remove the import on line 3 :)

**Review by dbczumar — APPROVED** [review]
LGTM once we remove the unused import. Thanks @kevingreer ! :D
