### PR TITLE
Fix tag cutoff in experiments table

### LINKED ISSUE #20867: [BUG] Experiment tags are cut off in Experiments table when exceeding column width
### MLflow version

bf8d0e270d11f8378908d3b0e1dceb412bd07f56

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Tahoe 26.2
- **Python version**: 3.10.19
- **yarn version, if running the dev UI**: 4.12.0

### Describe the problem

When multiple tags are added to an experiment, the Tags column in the Experiments table does not handle overflow properly. If the combined width of the tags exceeds the available column space, the tags are visually cut off instead of:
- wrapping to the next line,
- truncating with ellipsis, or
- providing horizontal scroll / tooltip for full visibility.

As a result, tag values become partially unreadable in the Experiments table view.

https://github.com/user-attachments/assets/3722bb65-4981-4c2c-a063-13d1279503b2

### Steps to reproduce the bug

1. Go to the MLflow Experiments page
1. Create or edit an experiment
1. Add multiple tags

Observe that tags are cut off when they exceed the column width.

### Code to generate data required to reproduce the bug

N/A

### Is the console panel in DevTools showing errors relevant to the bug? Type 'N/A' if not applicable.

N/A

### Does the network panel in DevTools contain failed requests relevant to the bug? Type 'N/A' if not applicable.

N/A

### PR DESCRIPTION
**Pull request by nananosirova**
### Related Issues/PRs

Closes https://github.com/mlflow/mlflow/issues/20867

### What changes are proposed in this pull request?

When multiple tags were added to an experiment, extra tags were clipped with no visual indication. Now the first tag is shown inline and remaining tags are accessible via a "+N" popover. 

https://github.com/user-attachments/assets/86a42208-e2f9-477a-95c5-a5864191aa04

### How is this PR tested?

- [ ] Existing unit/integration tests
- [x] New unit/integration tests
- [x] Manual tests

### Does this PR require documentation update?

- [x] No.
- [x] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.
- [ ] Yes. Please link the corresponding PR or explain how you plan to update it.

#### Is this a user-facing change?

- [ ] No.
- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Fixed tag clipping in the Experiments table. Previously, tags beyond the available column width were silently clipped. Now the first tag is shown inline and remaining tags are accessible via a "+N" popover. 

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Minor releases are expected to contain larger changes, such as new features and improvements. Non-critical bug fixes and doc updates can be included as well. By default, your PR should target the next minor release.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Patch releases are typically only performed when there has been a major regression or bug in the latest release. For the sake of stability, your PR should not be included in a patch release unless it is a critical fix, or if the risk level of your PR is exceedingly low.

</details>

- [ ] This PR is critical and needs to be in the next patch release
- [x] This PR can wait for the next minor release

### CODE REVIEW

File: mlflow/server/js/src/experiment-tracking/components/ExperimentListTableTagsCell.tsx [hunk 1]
```diff
@@ -36,6 +39,7 @@ export const ExperimentListTableTagsCell: ExperimentTableColumnDef['cell'] = ({
         })}
         css={{
           flexShrink: 0,
+          marginLeft: visibleTagList.length > 1 ? theme.spacing.sm : 0,
```
Comment (TomeHirata) [inline mlflow/server/js/src/experiment-tracking/components/ExperimentListTableTagsCell.tsx]: let's use containsTags

Comment (nananosirova) [reply mlflow/server/js/src/experiment-tracking/components/ExperimentListTableTagsCell.tsx]: Thanks @TomeHirata, I changed it to `containsTags` as per your suggestion. 
Noting that this slightly changes the single tag case since the button now adds `theme.spacing.sm` on top the tag's existing spacing, so the gap between that one tag and the edit button now becomes larger. I'm happy to use a `hasMultipleTags` check if we want to preserve the spacing.

**Review by TomeHirata — APPROVED** [review]

**Comment by nananosirova** [comment]
@TomeHirata thank you for the review and approval! Just wanted to double check, is there anything else needed on my end for this to be merged, or is it ready to go? Thanks!
