### PR TITLE
Fix model registry to preserve run_id when registering models via UI

### LINKED ISSUE #18489: [BUG]  Model Registry shows no metadata when registering models through UI
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

## Environment
- **MLflow Client Version**: 3.3.1
- **MLflow Tracking Server Version**: 3.3.1

### System information

- **Deployment**: Remote tracking server with PostgreSQL backend
- **Artifact Storage**: S3-compatible object storage
- **Model Type**: SentenceTransformers models logged with `mlflow.sentence_transformers.log_model()`

### Describe the problem

Not sure if this is an API bug or an UI bug. When registering a model to the Model Registry by clicking the "Register" button in the MLflow UI (from a logged model connected to a run), the registered model version appears in the registry with **no useful metadata**:

- ❌ `run_id` is empty/null
- ❌ No tags are preserved
- ❌ No connection back to the source run
- ❌ No evaluation metrics visible
- ❌ Cannot determine which training run produced this model

This makes the Model Registry completely unusable for model selection and comparison.

## Steps to Reproduce

1. **Log a model during training with metrics:**
```python
# During training
model_info = mlflow.sentence_transformers.log_model(
    model,
    name="final_model",
    step=100
)

# Log metrics with model_id (MLflow 3.0 feature)
mlflow.log_metric(
    key="eval_accuracy",
    value=0.85,
    step=100,
    model_id=model_info.model_id
)
```

2. **Navigate to the run in MLflow UI**
   - The model appears under "Models" column (e.g., `final_model`)
   - Metrics are visible in the run and the LOGGED model

3. **Click on the model → Click "Register" button**
   - Register to a new or existing model registry name

4. **Navigate to Model Registry → View the registered model version**

## Expected Behavior

The registered model version should show:
- ✅ `run_id` pointing back to the source training run
- ✅ Tags with key information (training params, dataset, etc.)
- ✅ Link to view the original run
- ✅ Evaluation metrics (or tags containing metrics)
- ✅ Model metadata that was attached during logging

## Actual Behavior

The registered model version shows:
- ❌ `run_id`: empty/null
- ❌ `tags`: {}
- ❌ `source`: `mlflow-artifacts:/14/models/m-<model_id>/artifacts`
- ❌ No way to trace back to the training run
- ❌ No metrics or performance information

### API Output Example:
```python
from mlflow.tracking import MlflowClient
client = MlflowClient()

versions = client.search_model_versions("name='my_model'")
version = versions[0]

print(f"Run ID: {version.run_id}")  # Output: ""
print(f"Tags: {version.tags}")      # Output: {}
print(f"Source: {version.source}")  # Output: mlflow-artifacts:/14/models/m-25aad0dd.../artifacts
```

## Root Cause Analysis

When registering via the UI, MLflow appears to use the **artifact URI** of the logged model (`mlflow-artifacts:/...`) rather than the **run URI** (`runs:/<run_id>/<model_name>`).

This breaks the link between the registered model and its source run, losing all context and metadata.

If this isn't a bug but I'm just logging the model wrong even better. But I couldn't find how to do it correctly.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```
#!/usr/bin/env python3
"""
Minimal reproducible test case for MLflow Model Registry issue.

This script demonstrates the problem where models registered via the UI
lose their run_id connection.

To reproduce:
1. Run this script
2. Open MLflow UI and navigate to the experiment
3. Click on the logged model in the run
4. Click "Register" button in the UI
5. Check the Model Registry - run_id will be empty

Expected: Registered model should have run_id and tags
Actual: Registered model has empty run_id and no tags
"""

import mlflow
import mlflow.sklearn
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score


def train_and_log_model():
    """Train a simple model and log it to MLflow with metrics."""
    
    # Generate dummy data
    X, y = make_classification(n_samples=1000, n_features=20, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Train model
    model = RandomForestClassifier(n_estimators=10, random_state=42)
    model.fit(X_train, y_train)
    
    # Evaluate
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    # Log to MLflow
    mlflow.set_experiment("mlflow_bug_reproduction")
    
    with mlflow.start_run(run_name="test_model_logging") as run:
        # Log parameters
        mlflow.log_param("n_estimators", 10)
        mlflow.log_param("random_state", 42)
        
        # Log metrics
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("f1_score", f1)
        
        # Log model WITH step parameter (MLflow 3.0 feature)
        model_info = mlflow.sklearn.log_model(
            sk_model=model,
            artifact_path="model",
            registered_model_name=None,  # Don't register yet
            step=100,  # This is the MLflow 3.0 feature
        )
        
        run_id = run.info.run_id
        
        print("=" * 80)
        print("Model logged successfully!")
        print("=" * 80)
        print(f"Run ID: {run_id}")
        print(f"Model ID: {model_info.model_id if hasattr(model_info, 'model_id') else 'N/A'}")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"F1 Score: {f1:.4f}")
        print()
        print("=" * 80)
        print("NEXT STEPS TO REPRODUCE THE BUG:")
        print("=" * 80)
        print("1. Open MLflow UI in your browser")
        print("2. Navigate to experiment: mlflow_bug_reproduction")
        print("3. Open the run: test_model_logging")
        print("4. You'll see the model under 'Models' or 'Artifacts'")
        print("5. Click on the model")
        print("6. Click the 'Register' button in the UI")
        print("7. Register it with name: 'test_registered_model'")
        print()
        print("Then run this command to verify the bug:")
        print(f"   python mlflow_verify_issue.py")
        print("=" * 80)
        
        return run_id


if __name__ == "__main__":
    run_id = train_and_log_model()


```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow model serving, deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/prompt`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/projects`: MLproject format, project running backends
- [x] `area/uiux`: Front-end, user experience, plotting
- [ ] `area/docs`: MLflow documentation pages

### PR DESCRIPTION
**Pull request by serena-ruan**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/serena-ruan/mlflow/pull/18501?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/18501/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/18501/merge#subdirectory=libs/skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/18501/merge
```

</p>
</details>

### Related Issues/PRs

Resolve #18489

### What changes are proposed in this pull request?

Fix the UI to preserve `run_id` and maintain traceability when registering models through the MLflow UI. The fix constructs proper source URIs:
- For logged models (MLflow 3.0+): Use `models:/{model_id}` format
- For regular artifacts: Use `runs:/{run_id}/{artifact_path}` format
- Fallback to absolute URI for backward compatibility

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests (5 new test cases)
- [x] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.

#### Is this a user-facing change?

- [x] Yes. Give a description of this change to be included in the release notes for MLflow users.

Fixed bug where models registered via UI lost their `run_id` connection, making them untraceable to source training runs. The UI now correctly preserves run metadata and displays "Source Run" links.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes

#### Should this PR be included in the next patch release?

- [x] Yes (this PR will be cherry-picked and included in the next patch release)

### CODE REVIEW

**Review by TomeHirata — APPROVED** [review]
LGTM!

File: mlflow/server/js/src/model-registry/components/RegisterModel.tsx [hunk 1]
```diff
@@ -131,7 +131,19 @@ export class RegisterModelImpl extends React.Component<RegisterModelImplProps, R
...
+      // 2. For regular artifacts with run context, use runs:/<run_id>/<model_path> format
+      // 3. Otherwise, fall back to the absolute artifact URI for backward compatibility
+      let sourceUri;
+      if (loggedModelId) {
+        sourceUri = `models:/${loggedModelId}`;
+      } else if (modelRelativePath && runUuid) {
+        sourceUri = `runs:/${runUuid}/${modelRelativePath}`;
+      } else {
+        sourceUri = modelPath;
+      }
```
Comment (daniellok-db) [inline mlflow/server/js/src/model-registry/components/RegisterModel.tsx]: nit: can be condensed slightly
```suggestion
      let sourceUri = modelPath;
      if (loggedModelId) {
        sourceUri = `models:/${loggedModelId}`;
      } else if (modelRelativePath && runUuid) {
        sourceUri = `runs:/${runUuid}/${modelRelativePath}`;
      }
```

**Review by daniellok-db — APPROVED** [review]
lgtm
