### PR TITLE
Fix: "Source Run" field in Model Version UI page points to wrong run model artifact in Run UI page

### LINKED ISSUE #8150: [BUG] "Source Run" field in Model Version UI page points to wrong run model artifact in Run UI page
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.2.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

If you have logged more than one model artifact in a run, the "Source Run" field of the Model Version UI page always links to the last model artifact in the Run UI page. 

In addition, the "Source Run" field name should be renamed "Source Model" and the model artifact name should be appended to the run name that appears in the field. So instead of `my-run` it should be `my-run/my-correct-model`.

This bug appears in both OSS and Databricks MLflow.

### Steps to reproduce the bug

Create a run and log two models.
Register the models as two versions in a registered model.
Go to the version UI page of the first model you registered as a version (see attached screenshot 1).
Click on the "Source Run" link and it will take you to the Run UI page and it highlights the last model artifact (see attached screenshot 2).

01_version_ui_page
02_run_ui_page

### Code to generate data required to reproduce the bug

[test_model_version_source.py.txt](https://github.com/mlflow/mlflow/files/11133650/test_model_version_source.py.txt)

### Is the console panel in DevTools showing errors relevant to the bug?

_No response_

### Does the network panel in DevTools contain failed requests relevant to the bug?

_No response_

### PR DESCRIPTION
**Pull request by WeichenXu123**
## Related Issues/PRs

 #8150

## What changes are proposed in this pull request?

Fix: "Source Run" field in Model Version UI page points to wrong run model artifact in Run UI page

Closes #8150

## How is this patch tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests (describe details, including test results, below)

manually test code:

```
import mlflow

import mlflow.sklearn
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
sk_model = tree.DecisionTreeClassifier()
sk_model = sk_model.fit(iris.data, iris.target)

with mlflow.start_run() as run:
    run_id = run.info.run_id
    print(run_id)
    mlflow.sklearn.log_model(sk_model, "model1")
    mlflow.sklearn.log_model(sk_model, "model2")

    mlflow.register_model(f"runs:/{run_id}/model1", "model01")
    mlflow.register_model(f"runs:/{run_id}/model2", "model02")

```

## Does this PR change the documentation?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js [hunk 1]
```diff
@@ -316,8 +316,15 @@ export class ModelVersionViewImpl extends React.Component {
         </a>
       );
     } else if (runInfo) {
+      const artifactPath = modelSource.substring(modelSource.indexOf('/artifacts/') + 11);
```
Comment (dbczumar) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:319]: @dbczumar Test the case where source run is defined but `source` lives outside the run (strange case, but could happen)

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js [hunk 2]
```diff
@@ -490,7 +497,7 @@ const mapStateToProps = (state, ownProps) => {
   const { modelName } = ownProps;
   const { version } = ownProps.modelVersion;
   const tags = getModelVersionTags(modelName, version, state);
-  return { tags };
+  return { tags, modelSource: ownProps.modelVersion.source };
```
Comment (hubertzub-db) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:500]: not sure if it's possible but let's make make it defensive against dereferencing exceptions
```suggestion
  return { tags, modelSource: ownProps.modelVersion?.source };
```

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js (hunk 1 above)
Comment (hubertzub-db) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:319]: - please fix lint issues
- let's assert that `modelSource` exists
- `11` seems to be a magic value here - what about `.+\/artifact\/(.+)$` regex wrapped in utility function to make it bit more elegant? ✨

File: mlflow/server/js/src/experiment-tracking/routes.js [hunk 3]
```diff
@@ -24,8 +24,12 @@ class Routes {
 
   static experimentPageSearchRoute = '/experiments/:experimentId/:searchString';
 
-  static getRunPageRoute(experimentId, runUuid) {
-    return `/experiments/${experimentId}/runs/${runUuid}`;
+  static getRunPageRoute(experimentId, runUuid, artifactPath = null) {
+    const path = `/experiments/${experimentId}/runs/${runUuid}`;
+    if (artifactPath) {
+      return path + `/artifactPath/${artifactPath}`;
```
Comment (harupy) [inline mlflow/server/js/src/experiment-tracking/routes.js:30]:
```suggestion
      return `${path}/artifactPath/${artifactPath}`;
```

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js [hunk 4]
```diff
@@ -316,8 +317,18 @@ export class ModelVersionViewImpl extends React.Component {
         </a>
       );
     } else if (runInfo) {
+      if (!modelSource) {
+        throw new Error('model source is missing.');
+      }
+      const artifactPath = modelSource.match(/.+\/artifacts\/(.+)$/)[1];
```
Comment (harupy) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: Does this work fine with a model logged with `mlflow.sklearn.log_model(sk_model, "artifacts/foo/bar")`?

[the remark this answers is not in the document]
Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: in case of absence or malformation of `modelSource`, we can just display a bare link to the run without artifact path

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: this is a good case for a unit test - is it possible to add a few jest tests here?

Comment (harupy) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: This line seems to assume that `modelSource` always ends with `/artifacts/...`. What if it doesn't?

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: Good catch. My first version code works fine with the case but using regex does not work with the case.
Any way to force the regex to match from left side ?

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: @WeichenXu123 apologies for introducing regression, still I believe regex might be more robust compared to `indexOf`

> My first version code works fine with the case but using regex does not work with the case.

Please note that `indexOf()` returns -1 when a substring is not found, so even if `modelSource` does not contain `/artifacts/` part at all, `modelSource.indexOf('/artifacts/') + 11` will always yield 10 regardless of the input. Is it ok?

> Any way to force the regex to match from left side ?

If you want to match the beginning of the string, you can use `^` wildcard. Still, I'm willing to help with this - can you explain what are the possible/acceptable inputs for `modelSource`?

Not sure what are the acceptable set of input values

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: I think valid source string might be：
`file:///path/to/mlruns/{experiment_id}/{run_id}/artifacts/{artifact_path}`
or
`mlflow-artifacts:/{experiment_id}/{run_id}/artifacts/{artifact_path}`

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: I think I found solution for regex, we can use lazy mode matching:

`modelSource.match(/.+?\/artifacts\/(.+)$/)[1];` (appended `+` after the first `.+`)

Ref: https://javascript.info/regexp-greedy-and-lazy#lazy-mode

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: @WeichenXu123 using lazy mode might cause `/artifacts/` being in the configurable part to be processed instead of ignored.
Please refer to
https://regex101.com/r/W08owe/1
this is the result

Screen Shot 2023-04-04 at 16 55 19

is it sufficient for the use case?

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: @hubertzub-db 

So we cannot use lazy mode, we should match the run ID in regex, like `modelSource.match(/{run_id}\/artifacts\/(.+)$/)[1];`

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: I'm a little lost now 🤔
doesn't the [example above ](https://regex101.com/r/c8aa8o/1) (one not using lazy mode) solve all use cases already? if not, let me know about any exception so we can fix it

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: @hubertzub-db 

`.+\/artifacts\/(.+)` does not work with such special case:

`mlflow-artifacts:/{experiment_id}/{run_id}/artifacts/artifacts/aa/bb`

the correct artifact path for the example is `artifacts/aa/bb` but `modelSource.match(/.+\/artifacts\/(.+)$/)[1]` returns `aa/bb`

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js:323]: @WeichenXu123 gotcha, didn't account for this edge case 😮 
Then I think you're right, let's use `run_id` - you can create a regexp on the fly:
```
const path = modelSource?.match(
  new RegExp(`/${runInfo.getRunUuid()}/artifacts/(.+)`),
)?.[1];
```
this should work and catch everything after first `/artifacts/` occurence following the run id, including other `artifacts` subpath.

Another tip: instead of routing the variable through `mapStateToProps()`, you can use it directly in the `resolveRunLink()` function using `modelVersion.source` since `modelVersion` is already extracted from the props.

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: What's the cases it does not ends with /artifacts/... ? 

I think the source string is
```
[file|s3|...]:///path/to/mlruns/{experiment_id}/{run_id}/artifacts/{artifact_path}
```
or
```
mlflow-artifacts:/{experiment_id}/{run_id}/artifacts/{artifact_path}
```

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: @hubertzub-db Thank you. I updated my PR.

I want to make `modelSource?.match(new RegExp(`/${runInfo.getRunUuid()}/artifacts/(.+)`),)?.[1]` to be a utility function `extract_artifact_path_from_model_source` and then add a unit test for it. Which place should I put this utility function ?

Comment (hubertzub-db) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: eh so the problem is that our general `Utils.js` is way too big already - I propose to either create `src/model-registry/utils/VersionUtils.js` file and a corresponding test file.

Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: Test was added !:)

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js (hunk 1 above)
Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: @dbczumar Any updates for this comment ? :)

File: mlflow/server/js/src/model-registry/utils/VersionUtil.ts
Comment (hubertzub-db) [inline mlflow/server/js/src/model-registry/utils/VersionUtil.ts:1]: the only feedback I have here is to rename it to `VersionUtils` to be consistent with the other files in the directory

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js [hunk 5]
```diff
@@ -490,7 +502,7 @@ const mapStateToProps = (state, ownProps) => {
   const { modelName } = ownProps;
   const { version } = ownProps.modelVersion;
   const tags = getModelVersionTags(modelName, version, state);
-  return { tags };
+  return { tags, modelSource: ownProps.modelVersion?.source };
```
Comment (hubertzub-db) [inline mlflow/server/js/src/model-registry/components/ModelVersionView.js:505]: source is already in props (`ownProps`), you're mapping props to props here :) 
you can just use `this.props.modelVersion?.source` in line # 323

**Review by hubertzub-db — APPROVED** [review]
lgtm with two nits left

**Comment by WeichenXu123** [comment]
CC @dbczumar @harupy Do you have more comments for this PR ? Thank you!

File: mlflow/server/js/src/model-registry/utils/VersionUtils.ts [hunk 6]
```diff
@@ -0,0 +1,6 @@
+/**
+ * Extract artifact path from provided `modelSource` string
+ */
+export function extractArtifactPathFromModelSource(modelSource: string, runId: string) {
```
Comment (harupy) [inline mlflow/server/js/src/model-registry/utils/VersionUtils.ts:4]: Can we add a return type?

File: mlflow/server/js/src/experiment-tracking/routes.js (hunk 3 above)
Comment (harupy) [inline mlflow/server/js/src/experiment-tracking/routes.js:30]: Reposting https://github.com/mlflow/mlflow/pull/8156/files#r1157176701

File: mlflow/server/js/src/model-registry/utils/VersionUtils.ts [hunk 7]
```diff
@@ -0,0 +1,6 @@
...
+  return modelSource?.match(new RegExp(`/${runId}/artifacts/(.+)`))?.[1];
```
Comment (harupy) [inline mlflow/server/js/src/model-registry/utils/VersionUtils.ts:5]: Do we need optional chaining for `modelSource`?

**Review by harupy — APPROVED** [review]
LGTM once the remaining comments are addressed

File: mlflow/server/js/src/model-registry/utils/VersionUtils.ts (hunk 6 above)
Comment (harupy) [reply mlflow/server/js/src/model-registry/utils/VersionUtils.ts:4]: @hubertzub-db Makes sense!

File: mlflow/server/js/src/model-registry/components/ModelVersionView.js (hunk 1 above)
Comment (WeichenXu123) [reply mlflow/server/js/src/model-registry/components/ModelVersionView.js]: In latest code, if model source is empty or parsing model source failed, it will still jump to the run page. So for some edge case the page won't be broken.
