### PR TITLE
Fix Issue 17348: Support basic auth in TypeScript SDK

### LINKED ISSUE #17348: Issue: Authentication Problem with MLflow Tracing on Deployed Server (OIDC) Using JS/TS SDK
Description
I set up MLflow tracing using the TypeScript + OpenAI quickstart:
https://mlflow.org/docs/latest/genai/tracing/quickstart/typescript-openai/

When I run with trackingUri = http://127.0.0.1:5000 (local MLflow server), everything works fine.
But when I switch trackingUri to my deployed MLflow server URL, trace export does not work as expected.

**Error Output**

Failed to export trace tr-dfd44ea360ec3cb62aa4a52b04a6d69d: Error: API request failed: {"name":"SyntaxError","message":"Unexpected '<'","at":1,"text":"<!DOCTYPE html>\n<html lang=\"en-US\">\n\n<head>\n    <title>Login</title>\n    <link rel=\"stylesheet\" href=\"/oidc/static/style.css\">\n    <link rel=\"shortcut icon\" href=\"/oidc/static/favicon.ico\">\n</head>\n\n<body>\n    <div class=\"content\">\n        <div class=\"center-block\">\n            <p>MLFlow authentication:</p>\n            <p><a href=\"/login\"><button>Login with Keycloak</button></a></p>\n        </div>\n    </div>\n    \n    <footer class=\"footer\">\n    <div class=\"footer-right\">\n        <p>&copy; 2025 OIDC Plugin for MLflow</p>\n    </div>\n    <div class=\"footer-right\">\n        <a href=\"[https://github.com/mlflow-oidc/\">\n](https://github.com/mlflow-oidc//%22%3E/n)            <svg aria-hidden=\"true\" focusable=\"false\" class=\"icon-github\" xmlns=\"[http://www.w3.org/2000/svg\"](http://www.w3.org/2000/svg/%22) viewBox=\"0 0 496 512\" width=\"16\" height=\"16\">\n                <path fill=\"currentColor\" d=\"M165.9 397.4c0 2-2.3 3.6-

It looks like instead of a JSON API response, the client is getting redirected to the login page served by the OIDC (Keycloak) plugin.

How can i authenticate and getting my traces on deployed mlflow

### PR DESCRIPTION
**Pull request by kevin-lyn**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/kevin-lyn/mlflow/pull/17436?quickstart=1)

#### Install mlflow from this PR

```
# mlflow
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17436/merge
# mlflow-skinny
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/17436/merge#subdirectory=libs/skinny
```

For Databricks, use the following command:

```
%sh curl -LsSf https://raw.githubusercontent.com/mlflow/mlflow/HEAD/dev/install-skinny.sh | sh -s pull/17436/merge
```

</p>
</details>

### Related Issues/PRs

#17348 

### What changes are proposed in this pull request?

Expose `username` and `password` in `MlflowClient` and the global config.
So that the TS SDK can surface the `username` and `password` in the header.

### How is this PR tested?

Manual tests with spinning up local server with `basic-auth` enabled.

### Does this PR require documentation update?

No

### Release Notes

Expose `username` and `password` in the TypeScript SDK.

#### Is this a user-facing change?

TypeScript SDK can now use the following to authenticate when basic auth is enabled in the tracking server:
```
import { init } from "mlflow-tracing";

init({
    trackingUri: "<your-tracking-server-uri>",
    experimentId: "<your-experiment-id>",
    username: "<your-username>",
    password: "<your-password>",
});
```

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/prompts`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [X] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [X] Yes (this PR will be cherry-picked and included in the next patch release)
- [ ] No (this PR will be included in the next minor release)

### CODE REVIEW

File: libs/typescript/core/src/clients/client.ts [hunk 1]
```diff
@@ -15,10 +15,22 @@ export class MlflowClient {
   private databricksToken?: string;
   /** Client implementation to upload/download trace data artifacts */
   private artifactsClient: ArtifactsClient;
+  /** `username` for basic auth */
+  private username?: string;
+  /** `password` for basic auth */
+  private password?: string;
```
Comment (daniellok-db) [inline libs/typescript/core/src/clients/client.ts]: should we name it `mlflowTrackingUsername` / `mlflowTrackingPassword` to make it clearer? i worry if people will confuse it for databricks username/password (let's update the comments to clarify as well)

**Review by daniellok-db — APPROVED** [review]
overall looks good!! congrats on your first OSS PR 😄 

left a comment about naming but LGTM after it's addressed. additionally, can we update the docs here with a new "MLflow Server with Auth" tab or something:

https://mlflow.org/docs/latest/genai/tracing/quickstart/typescript-openai/#initialize-the-tracing-sdk

code pointer:

https://github.com/mlflow/mlflow/blob/b5626f00ed9deaf704e784bf520e95fd12eb751a/docs/docs/genai/tracing/quickstart/typescript-openai.mdx?plain=1#L87

to build the docs, see the instructions here:

https://github.com/mlflow/mlflow/blob/b5626f00ed9deaf704e784bf520e95fd12eb751a/docs/README.md

TLDR, from `mlflow/docs` folder:
1. `npm install`
2. `npm run convert-notebooks` (i think you need to run this if it's your first time building the docs)
3. `npm start`

File: libs/typescript/core/src/clients/client.ts (hunk 1 above)
Comment (kevin-lyn) [reply libs/typescript/core/src/clients/client.ts]: makes sense. I probably would name it `trackingServerUsername` and `trackingServerPassword`, `mlflow` might be a bit redundant here. wdyt?

Comment (daniellok-db) [reply libs/typescript/core/src/clients/client.ts]: makes sense!

**Comment by kevin-lyn** [comment]
Force merging since the prettier lint error is on CHANGELOG which is not changed in this PR, probably some bad version in-between releases.
