### PR TITLE
Fix artifact image viewer to support animated GIF

### LINKED ISSUE #2042: [BUG] Gif animation stopped working after MLFlow 1.4 upgrade
### System information
- **OS Platform and Distribution (RHL 7.6)**:
- **MLflow installed from (binary, pip)**:
- **MLflow version (1.4.0)**:
- **Python version 3.6.8**:

### Describe the problem
Previously MLFlow UI artifacts viewer was able to display animated gifs which were VERY useful. Since 1.4 it stopped working.

It might be related to this PR: #1934

### PR DESCRIPTION
**Pull request by harupy**
## What changes are proposed in this pull request?

As reported in this issue #2042, the artifact viewer doesn't display animated gifs due to this PR #1934. The cause is `plotly` displays animated gifs as a static image. This PR proposes to change how the artifact viewer handles images as follows:

- For a static image, use `plotly`.
- For a animated gif, use `img` tag so that the image can animate.

handle-gif

## How is this patch tested?

Manually tested

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

### What component(s) does this PR affect?

- [x] UI
- [ ] CLI
- [ ] API
- [ ] REST-API
- [ ] Examples
- [ ] Docs
- [ ] Tracking
- [ ] Projects
- [ ] Artifacts
- [ ] Models
- [ ] Scoring
- [ ] Serving
- [ ] R
- [ ] Java
- [ ] Python

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [x] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by harupy** [comment]
@Zangr @smurching

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js [hunk 1]
```diff
@@ -52,64 +63,81 @@ class ShowArtifactImageView extends Component {
     img.src = this.getSrc();
   };
 
-  render() {
+  imageContainer = ({ children }) => (
```
Comment (Zangr) [inline mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: Is there a specific reason to define this as a class property instead of separately as for example `GifImageContainer`?

**Review by Zangr — COMMENTED** [review]
Could we have more comments on the cause of the issue and how it is fixed in the PR description section especially on the prop changes for <Plot/>?

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js (hunk 1 above)
Comment (harupy) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: I wrote this function to avoid writing the following code twice and reuse it in `renderGif` and `renderStaticImage`

```html
<div className="image-outer-container">
  <div className="image-container">{...}</div>
</div>
```

Comment (harupy) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: I just realized this function isn't necessary. We can put this nested `div` part in `render` like:

```javascript
render() {
  return(
    <div className="image-outer-container">
      <div className="image-container">
        {this.isGif() ? this.renderGif() : this. renderStaticImage()}
      </div>
    </div>
  )
}
```

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js [hunk 2]
```diff
@@ -52,61 +63,70 @@ class ShowArtifactImageView extends Component {
...
-  render() {
+  renderGif = () => {
+    const { loading } = this.state;
+    return (
+      <React.Fragment>
+        <div style={{ display: loading ? 'block' : 'none' }}>Loading...</div>
+        <img
+          src={this.getSrc()}
+          onLoad={() => this.setState({ loading: false })}
+          style={{ height: '100%', display: loading ? 'none' : 'block' }}
```
Comment (harupy) [inline mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: I need to add an alt text here to follow `jsx-a11y/alt-text`.

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js [hunk 3]
```diff
@@ -35,8 +35,19 @@ class ShowArtifactImageView extends Component {
...
+  isGif = () => {
+    return this.props.path.endsWith('.gif');
+  };
+
   fetchImage = () => {
     this.setState({ loading: true });
+
+    // gif
+    if (this.isGif()) {
+      return;
```
Comment (Zangr) [inline mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: Could we add the explanation in the PR description here as well?

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js (hunk 2 above)
Comment (Zangr) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: Sure, are you going to do it in this PR or the lint PR?

**Comment by harupy** [comment]
@Zangr I'll add alt text in this PR. You can merge #2083.

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js (hunk 3 above)
Comment (harupy) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: Actually, this is the part where I want to hear your thoughts. This is related to `Plotly` behavior. `Plotly` doesn't seem to provide a callback function that's called when image loading is done. That's why I load an image here, convert it to data URI and let `Plotly` just render it to manage the loading state. But, for gif, we don't have to do that because `img` tag can take care of that with `onLoad`.

Comment (Zangr) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: Oh, what I mean is we should add a comment here, similar to your explanation in the PR description. The approach LGTM.

Comment (harupy) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: @Zangr Oh, I misunderstood what you meant. I'll add comments.

File: mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js [hunk 4]
```diff
@@ -52,61 +67,72 @@ class ShowArtifactImageView extends Component {
...
-                  'lasso2d',
-                  'sendDataToCloud',
-                  'select2d',
-                  'toggleSpikelines',
-                ],
-              }}
-              useResizeHandler
-            />
-          }
+          {this.isGif() ? this.renderGif() : this.renderStaticImage()}
```
Comment (Zangr) [inline mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: One last request, would you mind adding a test for ShowArtifactImageView? Just basic rendering tests plus a test that mocks `renderGif` and `renderStaticImage` and make sure the correct one is call according to the file type?

Comment (harupy) [reply mlflow/server/js/src/components/artifact-view-components/ShowArtifactImageView.js]: ok I'll add it.

**Comment by harupy** [comment]
@Zhangr I added a test. What do you think?

**Review by Zangr — APPROVED** [review]
LGTM

**Comment by harupy** [comment]
@Zangr Thanks for merging!
